#!/usr/bin/env bash
# Sync mf-macos Debug defaults from repo-root local.env (same source as Expo / mf-desktop).
#
# Writes:
#   Configs/GeneratedEnv.xcconfig  — build-time Info.plist substitution (gitignored)
#   App Group files under group.com.masterfabric.projectTracker — runtime for app + widgets
#
# Usage:
#   ./scripts/sync-env.sh
#   npm run mf-macos:env   # from monorepo root
#   ./scripts/sync-desktop-env.sh --macos
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MACOS="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_ENV="${ROOT}/local.env"
OUT_XCCONFIG="${MACOS}/Configs/GeneratedEnv.xcconfig"
APP_GROUP_ID="group.com.masterfabric.projectTracker"
SUPPORT_REL="Library/Application Support/com.masterfabric.projectTracker"

if [[ -f "$LOCAL_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$LOCAL_ENV"
  set +a
  echo "Loaded ${LOCAL_ENV}"
else
  echo "WARN: missing ${LOCAL_ENV} — using safe defaults (no API key)." >&2
  echo "  Generate: ../masterfabric-particulars/scripts/print-mf-project-tracker-env.sh > local.env" >&2
fi

GRAPHQL_URL="${EXPO_PUBLIC_DEV_GRAPHQL_URL:-${EXPO_PUBLIC_GRAPHQL_URL:-http://127.0.0.1:8080/graphql}}"
GRAPHQL_URL="${GRAPHQL_URL//localhost/127.0.0.1}"
BUNDLE_ID="${EXPO_PUBLIC_MF_BUNDLE_ID:-com.masterfabric.monoExpo}"
API_KEY="${EXPO_PUBLIC_MF_APP_API_KEY:-${EXPO_PUBLIC_MF_API_KEY:-}}"
PARTICULAR="${EXPO_PUBLIC_MF_PROJECT_TRACKER_PARTICULAR:-project_tracker}"

# xcconfig: escape $ as $$
xc_escape() {
  printf '%s' "$1" | sed 's/\$/$$/g'
}

mkdir -p "$(dirname "$OUT_XCCONFIG")"
cat > "$OUT_XCCONFIG" <<EOF
// Generated by mf-macos/scripts/sync-env.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
// Do not commit. Regenerate: ./scripts/sync-env.sh  or  npm run mf-macos:env
GRAPHQL_URL = $(xc_escape "$GRAPHQL_URL")
MF_CLIENT_BUNDLE_ID = $(xc_escape "$BUNDLE_ID")
MF_APP_API_KEY = $(xc_escape "$API_KEY")
MF_PROJECT_TRACKER_PARTICULAR = $(xc_escape "$PARTICULAR")
EOF

echo "Wrote ${OUT_XCCONFIG}"
echo "  GRAPHQL_URL=${GRAPHQL_URL}"
echo "  MF_CLIENT_BUNDLE_ID=${BUNDLE_ID}"
echo "  MF_APP_API_KEY=$([ -n "$API_KEY" ] && echo '(set)' || echo '(empty — Sign In / Particular hops may fail)')"
echo "  MF_PROJECT_TRACKER_PARTICULAR=${PARTICULAR}"

# Seed App Group so a running menu bar / WidgetKit process sees the same values without rebuild.
GROUP_ROOT="${HOME}/Library/Group Containers/${APP_GROUP_ID}"
SUPPORT="${GROUP_ROOT}/${SUPPORT_REL}"
mkdir -p "$SUPPORT"
PREF="${GROUP_ROOT}/Library/Preferences/${APP_GROUP_ID}.plist"
mkdir -p "$(dirname "$PREF")"

write_key() {
  local key="$1"
  local value="$2"
  local file="${SUPPORT}/${key}.json"
  if [[ -n "$value" ]]; then
    printf '%s' "$value" > "$file"
  else
    rm -f "$file"
  fi
}

write_key "graphqlURL" "$GRAPHQL_URL"
write_key "mfBundleID" "$BUNDLE_ID"
write_key "mfProjectTrackerParticular" "$PARTICULAR"
if [[ -n "$API_KEY" ]]; then
  write_key "mfApiKey" "$API_KEY"
else
  rm -f "${SUPPORT}/mfApiKey.json"
fi

# Mirror into suite defaults. Sandboxed app + WidgetKit read the *Group Container*
# preferences plist — writing only the domain name hits ~/Library/Preferences and
# is invisible to the sandboxed process (refresh then runs without X-API-Key → Session expired).
if command -v defaults >/dev/null; then
  PREF_DOMAIN="${GROUP_ROOT}/Library/Preferences/${APP_GROUP_ID}"
  /usr/bin/defaults write "$PREF_DOMAIN" graphqlURL -string "$GRAPHQL_URL" 2>/dev/null || true
  /usr/bin/defaults write "$PREF_DOMAIN" mfBundleID -string "$BUNDLE_ID" 2>/dev/null || true
  /usr/bin/defaults write "$PREF_DOMAIN" mfProjectTrackerParticular -string "$PARTICULAR" 2>/dev/null || true
  if [[ -n "$API_KEY" ]]; then
    /usr/bin/defaults write "$PREF_DOMAIN" mfApiKey -string "$API_KEY" 2>/dev/null || true
  else
    /usr/bin/defaults delete "$PREF_DOMAIN" mfApiKey 2>/dev/null || true
  fi
  # Also write the non-sandbox domain for host-side scripts / defaults read.
  /usr/bin/defaults write "$APP_GROUP_ID" graphqlURL -string "$GRAPHQL_URL" 2>/dev/null || true
  /usr/bin/defaults write "$APP_GROUP_ID" mfBundleID -string "$BUNDLE_ID" 2>/dev/null || true
  /usr/bin/defaults write "$APP_GROUP_ID" mfProjectTrackerParticular -string "$PARTICULAR" 2>/dev/null || true
  if [[ -n "$API_KEY" ]]; then
    /usr/bin/defaults write "$APP_GROUP_ID" mfApiKey -string "$API_KEY" 2>/dev/null || true
  else
    /usr/bin/defaults delete "$APP_GROUP_ID" mfApiKey 2>/dev/null || true
  fi
fi

echo "Seeded App Group ${APP_GROUP_ID} → ${SUPPORT}"
echo "Next: ./scripts/install-debug.sh  (or rebuild) so Info.plist embeds the same keys."
