package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"time"

	"github.com/google/uuid"
	adminDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/admin/dto"
	adminTodoUC "github.com/masterfabric/masterfabric_go_basic/internal/application/admin/usecase"
	notificationDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/notification/dto"
	settingsDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/settings/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/domain/iam/policy"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// AdminSuspendUser is the resolver for the adminSuspendUser field.
func (r *mutationResolver) AdminSuspendUser(ctx context.Context, id uuid.UUID, suspend bool) (*model.AdminUserProfile, error) {
	resp, err := r.SuspendUserUC.Execute(ctx, &adminDTO.SuspendUserRequest{
		TargetUserID: id.String(),
		Suspend:      suspend,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}

// AdminChangeRole is the resolver for the adminChangeRole field.
func (r *mutationResolver) AdminChangeRole(ctx context.Context, id uuid.UUID, role model.UserRole) (*model.AdminUserProfile, error) {
	resp, err := r.ChangeRoleUC.Execute(ctx, &adminDTO.ChangeRoleRequest{
		TargetUserID: id.String(),
		Role:         graphqlRoleToString(role),
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}

// AdminSetUserStatus is the resolver for the adminSetUserStatus field.
func (r *mutationResolver) AdminSetUserStatus(ctx context.Context, id uuid.UUID, status model.UserStatus) (*model.AdminUserProfile, error) {
	resp, err := r.SetUserStatusUC.Execute(ctx, &adminDTO.SetUserStatusRequest{
		TargetUserID: id.String(),
		Status:       string(status),
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := r.DeleteUserUC.Execute(ctx, id); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminUpsertAppSetting is the resolver for the adminUpsertAppSetting field.
func (r *mutationResolver) AdminUpsertAppSetting(ctx context.Context, input model.AdminAppSettingInput) (*model.AdminAppSetting, error) {
	req := &settingsDTO.AdminUpsertAppSettingRequest{
		Key:         input.Key,
		Value:       input.Value,
		Description: "",
	}
	if input.Description != nil {
		req.Description = *input.Description
	}
	if input.IsPublic != nil {
		req.IsPublic = input.IsPublic
	}
	resp, err := r.AdminUpsertAppSettingUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return &model.AdminAppSetting{
		Key:         resp.Key,
		Value:       resp.Value,
		Description: resp.Description,
		IsPublic:    resp.IsPublic,
	}, nil
}

// AdminDeleteUserTodo is the resolver for the adminDeleteUserTodo field.
func (r *mutationResolver) AdminDeleteUserTodo(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := r.AdminDeleteUserTodoUC.Execute(ctx, id); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminUpdateUserTodo is the resolver for the adminUpdateUserTodo field.
func (r *mutationResolver) AdminUpdateUserTodo(ctx context.Context, input model.AdminUpdateUserTodoInput) (*model.UserTodo, error) {
	req := &adminTodoUC.AdminUpdateUserTodoRequest{
		TodoID:     input.ID,
		Title:      input.Title,
		Completed:  input.Completed,
		ClearDueAt: input.ClearDueAt,
	}
	if input.DueAt != nil {
		s := input.DueAt.UTC().Format(time.RFC3339)
		req.DueAt = &s
	}
	resp, err := r.AdminUpdateUserTodoUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return todoRespToModel(resp), nil
}

// AdminUsers is the resolver for the adminUsers field.
func (r *queryResolver) AdminUsers(ctx context.Context, page *int, pageSize *int) (*model.AdminUserList, error) {
	p, ps := 1, 20
	if page != nil {
		p = *page
	}
	if pageSize != nil {
		ps = *pageSize
	}
	resp, err := r.ListUsersUC.Execute(ctx, p, ps)
	if err != nil {
		return nil, mapErr(err)
	}
	users := make([]*model.AdminUserProfile, 0, len(resp.Users))
	for _, u := range resp.Users {
		users = append(users, adminUserToModel(u))
	}
	return &model.AdminUserList{
		Users:      users,
		TotalCount: resp.TotalCount,
		Page:       resp.Page,
		PageSize:   resp.PageSize,
	}, nil
}

// AdminUser is the resolver for the adminUser field.
func (r *queryResolver) AdminUser(ctx context.Context, id uuid.UUID) (*model.AdminUserProfile, error) {
	resp, err := r.GetUserByIDUC.Execute(ctx, id.String())
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}

// AdminAppSettings is the resolver for the adminAppSettings field.
func (r *queryResolver) AdminAppSettings(ctx context.Context) ([]*model.AdminAppSetting, error) {
	resp, err := r.AdminListAppSettingsUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	result := make([]*model.AdminAppSetting, 0, len(resp))
	for _, s := range resp {
		result = append(result, &model.AdminAppSetting{
			Key:         s.Key,
			Value:       s.Value,
			Description: s.Description,
			IsPublic:    s.IsPublic,
		})
	}
	return result, nil
}

// AdminUserSessions is the resolver for the adminUserSessions field.
func (r *queryResolver) AdminUserSessions(ctx context.Context, userID *uuid.UUID, limit *int) ([]*model.UserSession, error) {
	lim := 100
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	resp, err := r.ListUserSessionsUC.Execute(ctx, userID, lim)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.UserSession, 0, len(resp))
	for _, s := range resp {
		uid, _ := uuid.Parse(s.UserID)
		sid, _ := uuid.Parse(s.ID)
		createdAt, _ := time.Parse(time.RFC3339, s.CreatedAt)
		lastRefreshed, _ := time.Parse(time.RFC3339, s.LastRefreshedAt)
		orgNames := s.OrganizationNames
		if orgNames == nil {
			orgNames = []string{}
		}
		out = append(out, &model.UserSession{
			ID:                sid,
			UserID:            uid,
			UserEmail:         s.UserEmail,
			UserDisplayName:   s.UserDisplayName,
			OrganizationNames: orgNames,
			DeviceID:          s.DeviceID,
			Platform:          s.Platform,
			DeviceName:        s.DeviceName,
			CreatedAt:         createdAt,
			LastRefreshedAt:   lastRefreshed,
		})
	}
	return out, nil
}

// AdminSessionStats is the resolver for the adminSessionStats field.
func (r *queryResolver) AdminSessionStats(ctx context.Context) (*model.AdminSessionStats, error) {
	resp, err := r.GetSessionStatsUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	return &model.AdminSessionStats{
		TotalActiveSessions:    resp.TotalActiveSessions,
		UniqueActiveUsers:      resp.UniqueActiveUsers,
		TotalUsers:             resp.TotalUsers,
		TotalRegisteredDevices: resp.TotalRegisteredDevices,
	}, nil
}

// AdminUserDeletionImpact is the resolver for the adminUserDeletionImpact field.
func (r *queryResolver) AdminUserDeletionImpact(ctx context.Context, id uuid.UUID) (*model.AdminUserDeletionImpact, error) {
	resp, err := r.GetUserDeletionImpactUC.Execute(ctx, id)
	if err != nil {
		return nil, mapErr(err)
	}
	owned := make([]*model.AdminOwnedOrganizationDeletionImpact, 0, len(resp.OwnedOrganizations))
	for _, o := range resp.OwnedOrganizations {
		owned = append(owned, &model.AdminOwnedOrganizationDeletionImpact{
			OrganizationID:   o.OrganizationID,
			Name:             o.Name,
			OtherMemberCount: o.OtherMemberCount,
		})
	}
	return &model.AdminUserDeletionImpact{
		UserID:                           resp.UserID,
		Email:                            resp.Email,
		DisplayName:                      resp.DisplayName,
		OwnedTodoCount:                   resp.OwnedTodoCount,
		TodoAssigneeClearCount:           resp.TodoAssigneeClearCount,
		OrganizationMembershipCount:      resp.OrganizationMembershipCount,
		OwnedOrganizations:               owned,
		AddressCount:                     resp.AddressCount,
		DeviceCount:                      resp.DeviceCount,
		HasUserSettings:                  resp.HasUserSettings,
		NotificationReadCount:            resp.NotificationReadCount,
		SessionCount:                     resp.SessionCount,
		UserMessageCount:                 resp.UserMessageCount,
		PendingInvitationAsInviterCount:  resp.PendingInvitationAsInviterCount,
		OrganizationMessageAuthoredCount: resp.OrganizationMessageAuthoredCount,
		OrganizationNewsAuthoredCount:    resp.OrganizationNewsAuthoredCount,
		OtpCodeHistoryCount:              resp.OtpCodeHistoryCount,
	}, nil
}

// AdminUserOwnedTodos is the resolver for the adminUserOwnedTodos field.
func (r *queryResolver) AdminUserOwnedTodos(ctx context.Context, userID uuid.UUID) ([]*model.UserTodo, error) {
	resp, err := r.AdminListUserOwnedTodosUC.Execute(ctx, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.UserTodo, 0, len(resp))
	for _, t := range resp {
		out = append(out, todoRespToModel(t))
	}
	return out, nil
}

// AdminNotifications is the resolver for the adminNotifications field.
func (r *queryResolver) AdminNotifications(ctx context.Context, limit *int) ([]*model.NotificationPayload, error) {
	if err := policy.RequireAdmin(ctx); err != nil {
		return nil, mapErr(err)
	}
	userID := middleware.UserIDFromContext(ctx)
	userIDStr := ""
	if userID != uuid.Nil {
		userIDStr = userID.String()
	}
	l := 200
	if limit != nil && *limit > 0 {
		l = *limit
	}
	resp, err := r.ListNotificationsUC.Execute(ctx, &notificationDTO.ListNotificationsRequest{
		UserID:   userIDStr,
		Language: "",
		Limit:    l,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	result := make([]*model.NotificationPayload, 0, len(resp))
	for _, n := range resp {
		result = append(result, notificationWithReadToPayload(n))
	}
	return result, nil
}
