package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	authDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/auth/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/httpctx"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	resp, err := r.RegisterUC.Execute(ctx, &authDTO.RegisterRequest{
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: input.DisplayName,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return authRespToPayload(resp), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	resp, err := r.LoginUC.Execute(ctx, &authDTO.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
		ClientIP: httpctx.ClientIP(ctx),
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return loginRespToPayload(resp), nil
}

// LoginVerifyOtp is the resolver for the loginVerifyOTP field.
func (r *mutationResolver) LoginVerifyOtp(ctx context.Context, input model.LoginVerifyOTPInput) (*model.AuthPayload, error) {
	resp, err := r.LoginVerifyOTPUC.Execute(ctx, &authDTO.LoginVerifyOTPRequest{
		LoginToken: input.LoginToken,
		Code:       input.Code,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return authRespToPayload(resp), nil
}

// RefreshTokens is the resolver for the refreshTokens field.
func (r *mutationResolver) RefreshTokens(ctx context.Context, input model.RefreshInput) (*model.AuthPayload, error) {
	req := &authDTO.RefreshRequest{
		UserID:       input.UserID.String(),
		RefreshToken: input.RefreshToken,
	}
	if input.DeviceID != nil {
		req.DeviceID = *input.DeviceID
	}
	if input.Platform != nil {
		req.Platform = *input.Platform
	}
	if input.DeviceName != nil {
		req.DeviceName = *input.DeviceName
	}
	resp, err := r.RefreshUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return authRespToPayload(resp), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.LogoutInput) (bool, error) {
	callerID := middleware.UserIDFromContext(ctx)
	if callerID.String() == "00000000-0000-0000-0000-000000000000" {
		return false, domainErr.ErrUnauthorized
	}
	if callerID != input.UserID {
		return false, domainErr.ErrForbidden
	}

	err := r.LogoutUC.Execute(ctx, &authDTO.LogoutRequest{
		UserID:       input.UserID.String(),
		AccessToken:  input.AccessToken,
		RefreshToken: input.RefreshToken,
	})
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input model.RequestPasswordResetInput) (*model.PasswordResetRequestedPayload, error) {
	_ = r.RequestPasswordResetUC.Execute(ctx, input.Email, httpctx.ClientIP(ctx))
	return &model.PasswordResetRequestedPayload{Ok: true}, nil
}

// ResetPasswordWithOtp is the resolver for the resetPasswordWithOtp field.
func (r *mutationResolver) ResetPasswordWithOtp(ctx context.Context, input model.ResetPasswordWithOtpInput) (bool, error) {
	err := r.ResetPasswordWithOTPUC.Execute(ctx, &authDTO.ResetPasswordWithOtpRequest{
		Email:       input.Email,
		Code:        input.Code,
		NewPassword: input.NewPassword,
	})
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}
