package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	"github.com/masterfabric/masterfabric_go_basic/internal/application/device/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// RegisterDevice is the resolver for the registerDevice field.
func (r *mutationResolver) RegisterDevice(ctx context.Context, input model.RegisterDeviceInput) (*model.UserDevice, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	req := &dto.RegisterDeviceRequest{
		UserID:     userID.String(),
		DeviceID:   input.DeviceID,
		Platform:   input.Platform,
		DeviceName: derefStr(input.DeviceName),
		Model:      derefStr(input.Model),
		Brand:      derefStr(input.Brand),
		OSName:     derefStr(input.OsName),
		OSVersion:  derefStr(input.OsVersion),
		AppName:    derefStr(input.AppName),
		AppVersion: derefStr(input.AppVersion),
		AppBuild:   derefStr(input.AppBuild),
	}

	resp, err := r.RegisterDeviceUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return deviceRespToModel(resp), nil
}

// MyDevices is the resolver for the myDevices field.
func (r *queryResolver) MyDevices(ctx context.Context) ([]*model.UserDevice, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	devices, err := r.ListDevicesUC.Execute(ctx, userID)
	if err != nil {
		return nil, mapErr(err)
	}

	result := make([]*model.UserDevice, 0, len(devices))
	for _, d := range devices {
		result = append(result, deviceRespToModel(d))
	}
	return result, nil
}
