package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	feedbackdto "github.com/masterfabric/masterfabric_go_basic/internal/application/feedback/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
)

// SubmitFeedback is the resolver for the submitFeedback field.
func (r *mutationResolver) SubmitFeedback(ctx context.Context, input model.SubmitFeedbackInput) (*model.FeedbackThread, error) {
	req := &feedbackdto.SubmitFeedbackRequest{Message: input.Message}
	if input.Subject != nil {
		req.Subject = *input.Subject
	}
	if input.ContactEmail != nil {
		req.ContactEmail = *input.ContactEmail
	}
	resp, err := r.SubmitFeedbackUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return feedbackThreadDTOToModel(resp), nil
}

// AdminReplyToFeedback is the resolver for the adminReplyToFeedback field.
func (r *mutationResolver) AdminReplyToFeedback(ctx context.Context, input model.AdminReplyToFeedbackInput) (*model.FeedbackMessage, error) {
	resp, err := r.AdminReplyToFeedbackUC.Execute(ctx, &feedbackdto.AdminReplyRequest{
		ThreadID: input.ThreadID.String(),
		Message:  input.Message,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return feedbackMessageDTOToModel(resp), nil
}

// AdminDeleteFeedbackThread is the resolver for the adminDeleteFeedbackThread field.
func (r *mutationResolver) AdminDeleteFeedbackThread(ctx context.Context, threadID uuid.UUID) (bool, error) {
	if err := r.AdminDeleteFeedbackUC.Execute(ctx, threadID.String()); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// MyFeedbackThreads is the resolver for the myFeedbackThreads field.
func (r *queryResolver) MyFeedbackThreads(ctx context.Context) ([]*model.FeedbackThread, error) {
	list, err := r.ListMyFeedbackUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.FeedbackThread, 0, len(list))
	for _, t := range list {
		out = append(out, feedbackThreadDTOToModel(t))
	}
	return out, nil
}

// AdminFeedbackThreads is the resolver for the adminFeedbackThreads field.
func (r *queryResolver) AdminFeedbackThreads(ctx context.Context, limit *int) ([]*model.AdminFeedbackThread, error) {
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	list, err := r.AdminListFeedbackUC.Execute(ctx, lim)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.AdminFeedbackThread, 0, len(list))
	for _, row := range list {
		out = append(out, &model.AdminFeedbackThread{
			Thread:          feedbackThreadDTOToModel(row.Thread),
			UserEmail:       row.UserEmail,
			UserDisplayName: row.UserDisplayName,
		})
	}
	return out, nil
}
