package resolver

// helpers.go contains shared helper functions used across resolver files.
// This file is NOT regenerated by gqlgen.

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	adminDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/admin/dto"
	authDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/auth/dto"
	deviceDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/device/dto"
	feedbackDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/feedback/dto"
	mailDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/mail/dto"
	notificationDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/notification/dto"
	organizationDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/organization/dto"
	otpDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/otp/dto"
	prdto "github.com/masterfabric/masterfabric_go_basic/internal/application/productrelease/dto"
	settingsDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/settings/dto"
	todosDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/todos/dto"
	userDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/user/dto"
	notifModel "github.com/masterfabric/masterfabric_go_basic/internal/domain/notification/model"
	orgDomainModel "github.com/masterfabric/masterfabric_go_basic/internal/domain/organization/model"
	todoDomainModel "github.com/masterfabric/masterfabric_go_basic/internal/domain/todos/model"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
)

// uuidPtrToStr converts *uuid.UUID to *string for DTOs.
func uuidPtrToStr(u *uuid.UUID) *string {
	if u == nil || *u == uuid.Nil {
		return nil
	}
	s := u.String()
	return &s
}

// mapErr converts domain errors to GraphQL-friendly errors.
func mapErr(err error) error {
	var de *domainErr.DomainError
	if errors.As(err, &de) {
		return de // already has code + message (unwraps fmt.Errorf wrappers)
	}
	if de := mapPostgresToDomain(err); de != nil {
		return de
	}
	// #region agent log
	if err != nil && strings.Contains(strings.ToLower(err.Error()), "organization") {
		agentDebugLog6008d1("H_unmapped_org_err", "resolver/mapErr", "organization-related error not mapped to DomainError", map[string]any{
			"errSnippet": truncateRunes(err.Error(), 480),
		})
	}
	// #endregion
	return err
}

const agentDebugLogPath6008d1 = "/Users/srhnergul/Desktop/masaustu/masterfabric-expo-base/.cursor/debug-6008d1.log"

// #region agent log
func agentDebugLog6008d1(hypothesisID, location, message string, data map[string]any) {
	type line struct {
		SessionID    string         `json:"sessionId"`
		HypothesisID string         `json:"hypothesisId"`
		Location     string         `json:"location"`
		Message      string         `json:"message"`
		Data         map[string]any `json:"data,omitempty"`
		Timestamp    int64          `json:"timestamp"`
	}
	b, mErr := json.Marshal(line{
		SessionID:    "6008d1",
		HypothesisID: hypothesisID,
		Location:     location,
		Message:      message,
		Data:         data,
		Timestamp:    time.Now().UnixMilli(),
	})
	if mErr != nil {
		return
	}
	f, oErr := os.OpenFile(agentDebugLogPath6008d1, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if oErr != nil {
		return
	}
	_, _ = f.Write(append(b, '\n'))
	_ = f.Close()
}

func truncateRunes(s string, max int) string {
	if max <= 0 || len(s) <= max {
		return s
	}
	return s[:max] + "…"
}

// #endregion

// errorChainText joins Error() from err and each Unwrap for substring heuristics
// (some drivers wrap *pgconn.PgError so errors.As alone misses SQLSTATE in edge cases).
func errorChainText(err error) string {
	if err == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString(err.Error())
	for e := errors.Unwrap(err); e != nil; e = errors.Unwrap(e) {
		b.WriteString(" | ")
		b.WriteString(e.Error())
	}
	return b.String()
}

// mapPostgresToDomain turns PostgreSQL failures into DomainErrors so clients
// see a clear code/message instead of a generic INTERNAL_ERROR (still logged server-side).
func mapPostgresToDomain(err error) *domainErr.DomainError {
	chain := errorChainText(err)
	lower := strings.ToLower(chain)

	// String fallbacks first — work even when *pgconn.PgError is not visible to errors.As.
	if strings.Contains(chain, "42703") || strings.Contains(lower, "undefined_column") {
		return domainErr.New(
			"SCHEMA_OUT_OF_DATE",
			"Database schema is missing a required column. Run mf-go migrations (e.g. 021_user_todos_due_at for user todos due time, 022 for org project todos).",
			err,
		)
	}
	if strings.Contains(lower, "42p01") || strings.Contains(lower, "undefined_table") {
		return domainErr.New(
			"SCHEMA_OUT_OF_DATE",
			"Database is missing required tables. Run mf-go migrations on the server (e.g. 019_organization_projects).",
			err,
		)
	}

	var pe *pgconn.PgError
	if errors.As(err, &pe) {
		// #region agent log
		agentDebugLog6008d1("H_pg_err", "resolver/mapPostgresToDomain", "wrapped pgconn.PgError", map[string]any{
			"sqlState": pe.Code,
			"table":    pe.TableName,
			"msgLen":   len(pe.Message),
		})
		// #endregion
		switch pe.Code {
		case "42P01": // undefined_table
			return domainErr.New(
				"SCHEMA_OUT_OF_DATE",
				"Database is missing required tables. Run mf-go migrations on the server (e.g. 019_organization_projects).",
				err,
			)
		case "42703": // undefined_column
			return domainErr.New(
				"SCHEMA_OUT_OF_DATE",
				"Database schema is missing a required column. Run mf-go migrations (e.g. 020_organization_project_todo_assignee for project todo assignee).",
				err,
			)
		case "23503": // foreign_key_violation
			return domainErr.New(
				"VALIDATION_ERROR",
				"Referenced user or relation is invalid for this operation.",
				err,
			)
		default:
			return domainErr.New(
				"DATABASE_ERROR",
				fmt.Sprintf("The database rejected this operation (SQLSTATE %s). Ensure migrations are applied and check server logs.", pe.Code),
				err,
			)
		}
	}
	if strings.Contains(lower, "due_at") &&
		(strings.Contains(lower, "does not exist") || strings.Contains(lower, "column")) {
		return domainErr.New(
			"SCHEMA_OUT_OF_DATE",
			"Database schema is missing due_at on todos. Run migrations 021_user_todos_due_at and 022_organization_project_todos_due_at.",
			err,
		)
	}
	if strings.Contains(lower, "assigned_to_user_id") &&
		(strings.Contains(lower, "does not exist") || strings.Contains(lower, "column")) {
		return domainErr.New(
			"SCHEMA_OUT_OF_DATE",
			"Database schema is missing assigned_to_user_id on organization project todos. Run migration 020_organization_project_todo_assignee.",
			err,
		)
	}
	if strings.Contains(lower, "organization_projects") &&
		(strings.Contains(lower, "does not exist") || strings.Contains(lower, "unknown relation")) {
		// #region agent log
		agentDebugLog6008d1("H_schema_string_match", "resolver/mapPostgresToDomain", "heuristic missing table", map[string]any{})
		// #endregion
		return domainErr.New(
			"SCHEMA_OUT_OF_DATE",
			"Database is missing required tables. Run mf-go migrations on the server (e.g. 019_organization_projects).",
			err,
		)
	}
	return nil
}

func adminMailDTOToModel(resp *mailDTO.AdminMailSMTPSettingsResponse) *model.AdminMailSMTPSettings {
	if resp == nil {
		return nil
	}
	return &model.AdminMailSMTPSettings{
		Enabled:            resp.Enabled,
		Host:               resp.Host,
		Port:               resp.Port,
		Username:           resp.Username,
		PasswordConfigured: resp.PasswordConfigured,
		FromAddress:        resp.FromAddress,
		FromName:           resp.FromName,
		SubjectPrefix:      resp.SubjectPrefix,
		ImplicitTLS:        resp.ImplicitTLS,
		PlainNoTLS:         resp.PlainNoTLS,
		UpdatedAt:          resp.UpdatedAt,
	}
}

func productReleaseToModel(resp *prdto.ProductReleaseResponse) *model.ProductRelease {
	return &model.ProductRelease{
		Version:              resp.Version,
		ChangelogMarkdown:    resp.ChangelogMarkdown,
		UpdatedAt:            resp.UpdatedAt,
		UpdatedByDisplayName: resp.UpdatedByDisplayName,
	}
}

// loginRespToPayload converts a login DTO response to the GraphQL LoginPayload model.
func loginRespToPayload(resp *authDTO.LoginResponse) *model.LoginPayload {
	id, _ := uuid.Parse(resp.User.ID)
	user := &model.AuthUser{
		ID:          id,
		Email:       resp.User.Email,
		DisplayName: resp.User.DisplayName,
		AvatarURL:   resp.User.AvatarURL,
		Role:        graphqlRole(resp.User.Role),
	}
	payload := &model.LoginPayload{
		OtpRequired: resp.OTPRequired,
		User:        user,
	}
	if resp.OTPRequired {
		payload.LoginToken = &resp.LoginToken
	} else {
		payload.AccessToken = &resp.AccessToken
		payload.RefreshToken = &resp.RefreshToken
		ei := int(resp.ExpiresIn)
		payload.ExpiresIn = &ei
	}
	return payload
}

// authRespToPayload converts an auth DTO response to the GraphQL AuthPayload model.
func authRespToPayload(resp *authDTO.AuthResponse) *model.AuthPayload {
	id, _ := uuid.Parse(resp.User.ID)
	return &model.AuthPayload{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		ExpiresIn:    int(resp.ExpiresIn),
		User: &model.AuthUser{
			ID:          id,
			Email:       resp.User.Email,
			DisplayName: resp.User.DisplayName,
			AvatarURL:   resp.User.AvatarURL,
			Role:        graphqlRole(resp.User.Role),
		},
	}
}

// profileRespToModel converts a user profile DTO to the GraphQL UserProfile model.
// Pass a non-nil defaultAddr to populate the nested address field.
func profileRespToModel(resp *userDTO.UserProfileResponse, defaultAddr *userDTO.AddressResponse) *model.UserProfile {
	id, _ := uuid.Parse(resp.ID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)

	var dobStr *string
	if resp.DateOfBirth != nil {
		s := resp.DateOfBirth.Format("2006-01-02")
		dobStr = &s
	}

	return &model.UserProfile{
		ID:             id,
		Email:          resp.Email,
		DisplayName:    resp.DisplayName,
		Nickname:       resp.Nickname,
		AvatarURL:      resp.AvatarURL,
		Bio:            resp.Bio,
		Status:         model.UserStatus(toUpperStatus(resp.Status)),
		Role:           graphqlRole(resp.Role),
		CreatedAt:      createdAt,
		UpdatedAt:      updatedAt,
		PhoneNumber:    resp.PhoneNumber,
		DateOfBirth:    dobStr,
		Gender:         graphqlGender(resp.Gender),
		Location:       resp.Location,
		WebsiteURL:     resp.WebsiteURL,
		SocialTwitter:  resp.SocialTwitter,
		SocialGitHub:   resp.SocialGitHub,
		SocialLinkedIn: resp.SocialLinkedIn,
		Language:       resp.Language,
		TelegramChatID: resp.TelegramChatID,
		Address:        addressRespToModel(defaultAddr),
	}
}

// settingsRespToModel converts a settings DTO to the GraphQL UserSettingsPayload model.
func settingsRespToModel(userID uuid.UUID, resp *settingsDTO.UserSettingsResponse) *model.UserSettingsPayload {
	return &model.UserSettingsPayload{
		ID:              uuid.New(),
		UserID:          userID,
		NotificationsOn: resp.NotificationsOn,
		Theme:           stringToTheme(resp.Theme),
		Language:        resp.Language,
		Timezone:        resp.Timezone,
		OtpEnabled:      resp.OTPEnabled,
		UpdatedAt:       time.Now().UTC(),
	}
}

// stringToTheme converts a lowercase theme string to the GraphQL Theme enum.
func stringToTheme(s string) model.Theme {
	switch s {
	case "light":
		return model.ThemeLight
	case "dark":
		return model.ThemeDark
	default:
		return model.ThemeSystem
	}
}

// themeToString converts the GraphQL Theme enum to a lowercase storage string.
func themeToString(t model.Theme) string {
	switch t {
	case model.ThemeLight:
		return "light"
	case model.ThemeDark:
		return "dark"
	default:
		return "system"
	}
}

// graphqlRole converts a lowercase domain role string to the GraphQL UserRole enum.
func graphqlRole(role string) model.UserRole {
	switch role {
	case "admin":
		return model.UserRoleAdmin
	case "moderator":
		return model.UserRoleModerator
	default:
		return model.UserRoleUser
	}
}

// toUpperStatus converts a lowercase domain status string to the uppercase GraphQL value.
func toUpperStatus(status string) string {
	switch status {
	case "active":
		return "ACTIVE"
	case "inactive":
		return "INACTIVE"
	case "suspended":
		return "SUSPENDED"
	default:
		return "ACTIVE"
	}
}

// adminUserToModel converts an admin DTO response to the GraphQL AdminUserProfile model.
func adminUserToModel(resp *adminDTO.AdminUserResponse) *model.AdminUserProfile {
	id, _ := uuid.Parse(resp.ID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)

	var dobStr *string
	if resp.DateOfBirth != nil {
		s := resp.DateOfBirth.Format("2006-01-02")
		dobStr = &s
	}

	return &model.AdminUserProfile{
		ID:             id,
		Email:          resp.Email,
		DisplayName:    resp.DisplayName,
		Nickname:       resp.Nickname,
		AvatarURL:      resp.AvatarURL,
		Bio:            resp.Bio,
		Status:         model.UserStatus(toUpperStatus(resp.Status)),
		Role:           graphqlRole(resp.Role),
		CreatedAt:      createdAt,
		UpdatedAt:      updatedAt,
		PhoneNumber:    resp.PhoneNumber,
		DateOfBirth:    dobStr,
		Gender:         graphqlGender(resp.Gender),
		Location:       resp.Location,
		WebsiteURL:     resp.WebsiteURL,
		SocialTwitter:  resp.SocialTwitter,
		SocialGitHub:   resp.SocialGitHub,
		SocialLinkedIn: resp.SocialLinkedIn,
		Language:       resp.Language,
		TelegramChatID: resp.TelegramChatID,
	}
}

// graphqlRoleToString converts the GraphQL UserRole enum to the lowercase domain string
// expected by use-case inputs (e.g. ChangeRoleRequest.Role).
func graphqlRoleToString(role model.UserRole) string {
	switch role {
	case model.UserRoleAdmin:
		return "admin"
	case model.UserRoleModerator:
		return "moderator"
	default:
		return "user"
	}
}

// graphqlGender converts a lowercase domain gender string to the GraphQL Gender enum.
func graphqlGender(g string) model.Gender {
	switch g {
	case "male":
		return model.GenderMale
	case "female":
		return model.GenderFemale
	case "other":
		return model.GenderOther
	case "prefer_not_to_say":
		return model.GenderPreferNotToSay
	default:
		return model.GenderUnspecified
	}
}

// genderToString converts the GraphQL Gender enum pointer to the lowercase domain string.
// Returns "" (unspecified) when g is nil.
func genderToString(g *model.Gender) string {
	if g == nil {
		return ""
	}
	switch *g {
	case model.GenderMale:
		return "male"
	case model.GenderFemale:
		return "female"
	case model.GenderOther:
		return "other"
	case model.GenderPreferNotToSay:
		return "prefer_not_to_say"
	default:
		return ""
	}
}

// derefStr returns the string value or "" if nil.
func derefStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// deviceRespToModel converts a device DTO to the GraphQL UserDevice model.
func deviceRespToModel(resp *deviceDTO.DeviceResponse) *model.UserDevice {
	id, _ := uuid.Parse(resp.ID)
	userID, _ := uuid.Parse(resp.UserID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	return &model.UserDevice{
		ID:         id,
		UserID:     userID,
		DeviceID:   resp.DeviceID,
		Platform:   resp.Platform,
		DeviceName: resp.DeviceName,
		Model:      resp.Model,
		Brand:      resp.Brand,
		OsName:     resp.OSName,
		OsVersion:  resp.OSVersion,
		AppName:    resp.AppName,
		AppVersion: resp.AppVersion,
		AppBuild:   resp.AppBuild,
		CreatedAt:  createdAt,
		UpdatedAt:  updatedAt,
	}
}

// todoRespToModel converts a todo DTO to the GraphQL UserTodo model.
func todoRespToModel(resp *todosDTO.TodoResponse) *model.UserTodo {
	id, _ := uuid.Parse(resp.ID)
	userID, _ := uuid.Parse(resp.UserID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	out := &model.UserTodo{
		ID:        id,
		UserID:    userID,
		Title:     resp.Title,
		Completed: resp.Completed,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
	if resp.OrganizationID != nil {
		parsed, _ := uuid.Parse(*resp.OrganizationID)
		out.OrganizationID = &parsed
	}
	if resp.AssignedToUserID != nil {
		parsed, _ := uuid.Parse(*resp.AssignedToUserID)
		out.AssignedToUserID = &parsed
	}
	if resp.DueAt != nil {
		dueAt, _ := time.Parse(time.RFC3339, *resp.DueAt)
		out.DueAt = &dueAt
	}
	return out
}

func userTodoSubtaskDomainToModel(s *todoDomainModel.UserTodoSubtask) *model.UserTodoSubtask {
	if s == nil {
		return nil
	}
	return &model.UserTodoSubtask{
		ID:         s.ID,
		UserTodoID: s.UserTodoID,
		Title:      s.Title,
		Completed:  s.Completed,
		SortOrder:  s.SortOrder,
		CreatedAt:  s.CreatedAt,
		UpdatedAt:  s.UpdatedAt,
	}
}

func orgProjectTodoSubtaskDomainToModel(s *orgDomainModel.OrganizationProjectTodoSubtask) *model.OrganizationProjectTodoSubtask {
	if s == nil {
		return nil
	}
	return &model.OrganizationProjectTodoSubtask{
		ID:            s.ID,
		ProjectTodoID: s.ProjectTodoID,
		Title:         s.Title,
		Completed:     s.Completed,
		SortOrder:     s.SortOrder,
		CreatedAt:     s.CreatedAt,
		UpdatedAt:     s.UpdatedAt,
	}
}

// orgRespToModel converts an organization DTO to the GraphQL Organization model.
func orgRespToModel(resp *organizationDTO.OrganizationResponse) *model.Organization {
	id, _ := uuid.Parse(resp.ID)
	ownerID, _ := uuid.Parse(resp.OwnerUserID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	return &model.Organization{
		ID:           id,
		Name:         resp.Name,
		Description:  resp.Description,
		LogoURL:      resp.LogoURL,
		WebsiteURL:   resp.WebsiteURL,
		ContactEmail: resp.ContactEmail,
		OwnerUserID:  ownerID,
		CreatedAt:    createdAt,
		UpdatedAt:    updatedAt,
	}
}

// orgMemberRespToModel converts an organization member DTO to the GraphQL OrganizationMember model.
func orgMemberRespToModel(resp *organizationDTO.OrganizationMemberResponse) *model.OrganizationMember {
	id, _ := uuid.Parse(resp.ID)
	orgID, _ := uuid.Parse(resp.OrganizationID)
	userID, _ := uuid.Parse(resp.UserID)
	joinedAt, _ := time.Parse(time.RFC3339, resp.JoinedAt)
	nickname := resp.UserNickname
	if nickname == "" && len(resp.UserID) >= 8 {
		nickname = resp.UserID[:8] + "…" // fallback when user has no nickname
	}
	if nickname == "" {
		nickname = "—"
	}
	return &model.OrganizationMember{
		ID:               id,
		OrganizationID:   orgID,
		UserID:           userID,
		UserNickname:     nickname,
		Role:             orgMemberRoleToModel(resp.Role),
		MembershipStatus: orgMembershipStatusToModel(resp.MembershipStatus),
		JoinedAt:         joinedAt,
	}
}

func orgMembershipStatusToModel(s string) model.OrganizationMembershipStatus {
	switch s {
	case "suspended":
		return model.OrganizationMembershipStatusSuspended
	default:
		return model.OrganizationMembershipStatusActive
	}
}

// orgMemberRoleToModel converts a lowercase role string to the GraphQL enum.
func orgMemberRoleToModel(role string) model.OrganizationMemberRole {
	switch role {
	case "owner":
		return model.OrganizationMemberRoleOwner
	case "admin":
		return model.OrganizationMemberRoleAdmin
	default:
		return model.OrganizationMemberRoleMember
	}
}

func orgProjectRespToModel(resp *organizationDTO.OrganizationProjectResponse) *model.OrganizationProject {
	id, _ := uuid.Parse(resp.ID)
	orgID, _ := uuid.Parse(resp.OrganizationID)
	by, _ := uuid.Parse(resp.CreatedByUserID)
	ca, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	ua, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	return &model.OrganizationProject{
		ID:              id,
		OrganizationID:  orgID,
		Name:            resp.Name,
		Description:     resp.Description,
		CreatedByUserID: by,
		CreatedAt:       ca,
		UpdatedAt:       ua,
	}
}

func orgProjectMemberRespToModel(resp *organizationDTO.OrganizationProjectMemberResponse) *model.OrganizationProjectMember {
	id, _ := uuid.Parse(resp.ID)
	pid, _ := uuid.Parse(resp.ProjectID)
	uid, _ := uuid.Parse(resp.UserID)
	added, _ := time.Parse(time.RFC3339, resp.AddedAt)
	nick := resp.UserNickname
	if nick == "" && len(resp.UserID) >= 8 {
		nick = resp.UserID[:8] + "…"
	}
	if nick == "" {
		nick = "—"
	}
	return &model.OrganizationProjectMember{
		ID:           id,
		ProjectID:    pid,
		UserID:       uid,
		UserNickname: nick,
		AddedAt:      added,
	}
}

func orgProjectOrgParticipationDomainToModel(m *orgDomainModel.OrganizationProjectOrgParticipation) *model.OrganizationProjectOrgParticipation {
	if m == nil {
		return nil
	}
	var st model.OrganizationProjectOrgParticipationStatus
	switch m.Status {
	case orgDomainModel.OrganizationProjectOrgParticipationAccepted:
		st = model.OrganizationProjectOrgParticipationStatusAccepted
	case orgDomainModel.OrganizationProjectOrgParticipationDeclined:
		st = model.OrganizationProjectOrgParticipationStatusDeclined
	case orgDomainModel.OrganizationProjectOrgParticipationRevoked:
		st = model.OrganizationProjectOrgParticipationStatusRevoked
	default:
		st = model.OrganizationProjectOrgParticipationStatusPending
	}
	caps := string(m.Capabilities)
	if caps == "" {
		caps = "{}"
	}
	out := &model.OrganizationProjectOrgParticipation{
		ID:                        m.ID,
		ProjectID:                 m.ProjectID,
		ParticipantOrganizationID: m.ParticipantOrganizationID,
		Status:                    st,
		CapabilitiesJSON:          caps,
		InvitedByUserID:           m.InvitedByUserID,
		InvitedAt:                 m.InvitedAt,
		RespondedAt:               m.RespondedAt,
		CreatedAt:                 m.CreatedAt,
		UpdatedAt:                 m.UpdatedAt,
	}
	return out
}

func orgProjectTodoRespToModel(resp *organizationDTO.OrganizationProjectTodoResponse) *model.OrganizationProjectTodo {
	id, _ := uuid.Parse(resp.ID)
	pid, _ := uuid.Parse(resp.ProjectID)
	by, _ := uuid.Parse(resp.CreatedByUserID)
	ca, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	ua, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	var st model.OrganizationProjectTodoStatus
	switch strings.ToUpper(resp.Status) {
	case "DONE":
		st = model.OrganizationProjectTodoStatusDone
	default:
		st = model.OrganizationProjectTodoStatusOpen
	}
	var assigned *uuid.UUID
	if resp.AssignedToUserID != nil && *resp.AssignedToUserID != "" {
		if u, err := uuid.Parse(*resp.AssignedToUserID); err == nil {
			assigned = &u
		}
	}
	out := &model.OrganizationProjectTodo{
		ID:               id,
		ProjectID:        pid,
		Title:            resp.Title,
		Status:           st,
		CreatedByUserID:  by,
		AssignedToUserID: assigned,
		CreatedAt:        ca,
		UpdatedAt:        ua,
	}
	if resp.DueAt != nil {
		dueAt, _ := time.Parse(time.RFC3339, *resp.DueAt)
		out.DueAt = &dueAt
	}
	return out
}

func orgProjectPurchaseRespToModel(resp *organizationDTO.OrganizationProjectPurchaseResponse) *model.OrganizationProjectPurchase {
	id, _ := uuid.Parse(resp.ID)
	pid, _ := uuid.Parse(resp.ProjectID)
	by, _ := uuid.Parse(resp.CreatedByUserID)
	ca, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	ua, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	var st model.OrganizationProjectPurchaseStatus
	switch strings.ToUpper(strings.TrimSpace(resp.Status)) {
	case "PURCHASED":
		st = model.OrganizationProjectPurchaseStatusPurchased
	case "CANCELLED":
		st = model.OrganizationProjectPurchaseStatusCancelled
	default:
		st = model.OrganizationProjectPurchaseStatusRequested
	}
	return &model.OrganizationProjectPurchase{
		ID:              id,
		ProjectID:       pid,
		ProductName:     resp.ProductName,
		TaxRate:         resp.TaxRate,
		ProductPurpose:  resp.ProductPurpose,
		Price:           resp.Price,
		Quantity:        resp.Quantity,
		ProductLink:     resp.ProductLink,
		Status:          st,
		StatusNote:      resp.StatusNote,
		Currency:        resp.Currency,
		CreatedByUserID: by,
		CreatedAt:       ca,
		UpdatedAt:       ua,
	}
}

// orgInvitationRespToModel converts an organization invitation DTO to the GraphQL OrganizationInvitation model.
func orgInvitationRespToModel(resp *organizationDTO.OrganizationInvitationResponse) *model.OrganizationInvitation {
	id, _ := uuid.Parse(resp.ID)
	orgID, _ := uuid.Parse(resp.OrganizationID)
	inviterID, _ := uuid.Parse(resp.InviterID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	m := &model.OrganizationInvitation{
		ID:             id,
		OrganizationID: orgID,
		InviterID:      inviterID,
		InviteeEmail:   resp.InviteeEmail,
		Status:         orgInvitationStatusToModel(resp.Status),
		CreatedAt:      createdAt,
	}
	if resp.OrganizationName != "" {
		s := resp.OrganizationName
		m.OrganizationName = &s
	}
	if resp.InviterNickname != "" {
		s := resp.InviterNickname
		m.InviterNickname = &s
	}
	return m
}

// orgInvitationStatusToModel converts a lowercase status string to the GraphQL enum.
func orgInvitationStatusToModel(status string) model.OrganizationInvitationStatus {
	switch status {
	case "accepted":
		return model.OrganizationInvitationStatusAccepted
	case "declined":
		return model.OrganizationInvitationStatusDeclined
	case "revoked":
		return model.OrganizationInvitationStatusRevoked
	default:
		return model.OrganizationInvitationStatusPending
	}
}

func orgNewsRespToModel(resp *organizationDTO.OrganizationNewsResponse) *model.OrganizationNews {
	id, _ := uuid.Parse(resp.ID)
	orgID, _ := uuid.Parse(resp.OrganizationID)
	authorID, _ := uuid.Parse(resp.AuthorUserID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	return &model.OrganizationNews{
		ID:             id,
		OrganizationID: orgID,
		AuthorUserID:   authorID,
		AuthorNickname: resp.AuthorNickname,
		Title:          resp.Title,
		Description:    resp.Description,
		ImageURL:       resp.ImageURL,
		RichMetadata:   resp.RichMetadata,
		CreatedAt:      createdAt,
		UpdatedAt:      updatedAt,
	}
}

func orgMessageDTOToModel(resp *organizationDTO.OrganizationMessageResponse) *model.OrganizationMessage {
	id, _ := uuid.Parse(resp.ID)
	orgID, _ := uuid.Parse(resp.OrganizationID)
	authorID, _ := uuid.Parse(resp.AuthorUserID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	return &model.OrganizationMessage{
		ID:             id,
		OrganizationID: orgID,
		AuthorUserID:   authorID,
		AuthorNickname: resp.AuthorNickname,
		Body:           resp.Body,
		CreatedAt:      createdAt,
	}
}

// addressRespToModel converts an address DTO response to the GraphQL UserAddress model.
func addressRespToModel(resp *userDTO.AddressResponse) *model.UserAddress {
	if resp == nil {
		return nil
	}
	id, _ := uuid.Parse(resp.ID)
	userID, _ := uuid.Parse(resp.UserID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	return &model.UserAddress{
		ID:           id,
		UserID:       userID,
		Title:        resp.Title,
		AddressLine1: resp.AddressLine1,
		AddressLine2: resp.AddressLine2,
		City:         resp.City,
		State:        resp.State,
		PostalCode:   resp.PostalCode,
		Country:      resp.Country,
		IsDefault:    resp.IsDefault,
		CreatedAt:    createdAt,
		UpdatedAt:    updatedAt,
	}
}

// notificationWithReadToPayload converts a notification DTO with read status to GraphQL NotificationPayload.
func notificationWithReadToPayload(resp *notificationDTO.NotificationWithReadResponse) *model.NotificationPayload {
	id, _ := uuid.Parse(resp.ID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	m := &model.NotificationPayload{
		ID:        id,
		Title:     resp.Title,
		Message:   resp.Message,
		Type:      resp.Type,
		Category:  resp.Category,
		IsRead:    resp.IsRead,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
	if resp.Subtitle != "" {
		m.Subtitle = &resp.Subtitle
	}
	if resp.Icon != "" {
		m.Icon = &resp.Icon
	}
	if resp.Language != "" {
		m.Language = &resp.Language
	}
	if resp.ActionURL != "" {
		m.ActionURL = &resp.ActionURL
	}
	if resp.ImageURL != "" {
		m.ImageURL = &resp.ImageURL
	}
	if resp.Priority != "" {
		m.Priority = &resp.Priority
	}
	return m
}

// notificationRespToPayload converts a notification DTO (no read status) to GraphQL NotificationPayload.
func notificationRespToPayload(resp *notificationDTO.NotificationResponse, isRead bool) *model.NotificationPayload {
	id, _ := uuid.Parse(resp.ID)
	createdAt, _ := time.Parse(time.RFC3339, resp.CreatedAt)
	updatedAt, _ := time.Parse(time.RFC3339, resp.UpdatedAt)
	m := &model.NotificationPayload{
		ID:        id,
		Title:     resp.Title,
		Message:   resp.Message,
		Type:      resp.Type,
		Category:  resp.Category,
		IsRead:    isRead,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
	if resp.Subtitle != "" {
		m.Subtitle = &resp.Subtitle
	}
	if resp.Icon != "" {
		m.Icon = &resp.Icon
	}
	if resp.Language != "" {
		m.Language = &resp.Language
	}
	if resp.ActionURL != "" {
		m.ActionURL = &resp.ActionURL
	}
	if resp.ImageURL != "" {
		m.ImageURL = &resp.ImageURL
	}
	if resp.Priority != "" {
		m.Priority = &resp.Priority
	}
	return m
}

func domainNotificationToPayload(n *notifModel.Notification) *model.NotificationPayload {
	m := &model.NotificationPayload{
		ID:        n.ID,
		Title:     n.Title,
		Message:   n.Message,
		Type:      string(n.Type),
		Category:  n.Category,
		IsRead:    false,
		CreatedAt: n.CreatedAt,
		UpdatedAt: n.UpdatedAt,
	}
	if n.Subtitle != "" {
		m.Subtitle = &n.Subtitle
	}
	if n.Icon != "" {
		m.Icon = &n.Icon
	}
	if n.Language != "" {
		m.Language = &n.Language
	}
	if n.ActionURL != "" {
		m.ActionURL = &n.ActionURL
	}
	if n.ImageURL != "" {
		m.ImageURL = &n.ImageURL
	}
	if n.Priority != "" {
		m.Priority = &n.Priority
	}
	return m
}

func feedbackAuthorRole(s string) model.FeedbackAuthorRole {
	switch s {
	case "ADMIN":
		return model.FeedbackAuthorRoleAdmin
	default:
		return model.FeedbackAuthorRoleUser
	}
}

func feedbackMessageDTOToModel(m *feedbackDTO.FeedbackMessageResponse) *model.FeedbackMessage {
	id, _ := uuid.Parse(m.ID)
	tid, _ := uuid.Parse(m.ThreadID)
	return &model.FeedbackMessage{
		ID:         id,
		ThreadID:   tid,
		AuthorRole: feedbackAuthorRole(m.AuthorRole),
		Body:       m.Body,
		CreatedAt:  m.CreatedAt,
	}
}

func feedbackThreadDTOToModel(resp *feedbackDTO.FeedbackThreadResponse) *model.FeedbackThread {
	id, _ := uuid.Parse(resp.ID)
	var userID *uuid.UUID
	if resp.UserID != "" {
		if u, err := uuid.Parse(resp.UserID); err == nil {
			userID = &u
		}
	}
	msgs := make([]*model.FeedbackMessage, 0, len(resp.Messages))
	for _, m := range resp.Messages {
		if m != nil {
			msgs = append(msgs, feedbackMessageDTOToModel(m))
		}
	}
	return &model.FeedbackThread{
		ID:           id,
		UserID:       userID,
		ContactEmail: resp.ContactEmail,
		Subject:      resp.Subject,
		Status:       resp.Status,
		CreatedAt:    resp.CreatedAt,
		UpdatedAt:    resp.UpdatedAt,
		Messages:     msgs,
	}
}

// ── OTP helpers ─────────────────────────────────────────────────────────────

func gqlOTPPurposeToString(p model.OTPPurpose) string {
	switch p {
	case model.OTPPurposeLogin:
		return "login"
	case model.OTPPurposeVerifyIDEntity:
		return "verify_identity"
	case model.OTPPurposePasswordReset:
		return "password_reset"
	case model.OTPPurposeAccountActivate:
		return "account_activate"
	case model.OTPPurposeEmailChange:
		return "email_change"
	default:
		return "login"
	}
}

func gqlOTPChannel(ch string) model.OTPChannel {
	switch ch {
	case "admin_panel":
		return model.OTPChannelAdminPanel
	case "email":
		return model.OTPChannelEmail
	case "sms":
		return model.OTPChannelSms
	case "whatsapp":
		return model.OTPChannelWhatsapp
	case "telegram":
		return model.OTPChannelTelegram
	default:
		return model.OTPChannelAdminPanel
	}
}

func gqlOTPPurpose(p string) model.OTPPurpose {
	switch p {
	case "login":
		return model.OTPPurposeLogin
	case "verify_identity":
		return model.OTPPurposeVerifyIDEntity
	case "password_reset":
		return model.OTPPurposePasswordReset
	case "account_activate":
		return model.OTPPurposeAccountActivate
	case "email_change":
		return model.OTPPurposeEmailChange
	default:
		return model.OTPPurposeLogin
	}
}

func gqlOTPStatus(s string) model.OTPStatus {
	switch s {
	case "pending":
		return model.OTPStatusPending
	case "verified":
		return model.OTPStatusVerified
	case "expired":
		return model.OTPStatusExpired
	default:
		return model.OTPStatusPending
	}
}

func adminOTPsToModel(otps []*otpDTO.AdminOTPResponse) []*model.AdminOTPEntry {
	result := make([]*model.AdminOTPEntry, 0, len(otps))
	for _, o := range otps {
		id, _ := uuid.Parse(o.ID)
		uid, _ := uuid.Parse(o.UserID)
		result = append(result, &model.AdminOTPEntry{
			ID:         id,
			UserID:     uid,
			Code:       o.Code,
			Channel:    gqlOTPChannel(o.Channel),
			Purpose:    gqlOTPPurpose(o.Purpose),
			Status:     gqlOTPStatus(o.Status),
			Attempts:   o.Attempts,
			MaxRetries: o.MaxRetries,
			ExpiresAt:  o.ExpiresAt,
			VerifiedAt: o.VerifiedAt,
			CreatedAt:  o.CreatedAt,
		})
	}
	return result
}
