package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/masterfabric/masterfabric_go_basic/internal/application/mail/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
)

// AdminUpdateMailSMTPSettings is the resolver for the adminUpdateMailSmtpSettings field.
func (r *mutationResolver) AdminUpdateMailSMTPSettings(ctx context.Context, input model.AdminUpdateMailSMTPSettingsInput) (*model.AdminMailSMTPSettings, error) {
	req := &dto.AdminUpdateMailSMTPRequest{
		Enabled:       input.Enabled,
		Host:          input.Host,
		Port:          input.Port,
		Username:      input.Username,
		Password:      input.Password,
		FromAddress:   input.FromAddress,
		FromName:      input.FromName,
		SubjectPrefix: input.SubjectPrefix,
		ImplicitTLS:   input.ImplicitTLS,
		PlainNoTLS:    input.PlainNoTLS,
	}
	resp, err := r.UpdateAdminMailSMTPSettingsUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return adminMailDTOToModel(resp), nil
}

// AdminSendTestMail is the resolver for the adminSendTestMail field.
func (r *mutationResolver) AdminSendTestMail(ctx context.Context, input model.AdminSendTestMailInput) (bool, error) {
	if err := r.AdminSendTestMailUC.Execute(ctx, input.ToEmail); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminSendUserEmail is the resolver for the adminSendUserEmail field.
func (r *mutationResolver) AdminSendUserEmail(ctx context.Context, input model.AdminSendUserEmailInput) (bool, error) {
	if err := r.AdminSendUserEmailUC.Execute(ctx, input.UserID, input.Subject, input.Body); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminMailSMTPSettings is the resolver for the adminMailSmtpSettings field.
func (r *queryResolver) AdminMailSMTPSettings(ctx context.Context) (*model.AdminMailSMTPSettings, error) {
	resp, err := r.GetAdminMailSMTPSettingsUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	return adminMailDTOToModel(resp), nil
}
