package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	notificationDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/notification/dto"
	notificationUC "github.com/masterfabric/masterfabric_go_basic/internal/application/notification/usecase"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.ErrUnauthorized
	}
	err := r.MarkNotificationReadUC.Execute(ctx, &notificationDTO.MarkNotificationReadRequest{
		UserID:         userID.String(),
		NotificationID: id.String(),
	})
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.ErrUnauthorized
	}
	err := r.MarkAllNotificationsReadUC.Execute(ctx, &notificationUC.MarkAllNotificationsReadRequest{
		UserID: userID.String(),
	})
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminCreateNotification is the resolver for the adminCreateNotification field.
func (r *mutationResolver) AdminCreateNotification(ctx context.Context, input model.CreateNotificationInput) (*model.NotificationPayload, error) {
	req := &notificationDTO.CreateNotificationRequest{
		Title:    input.Title,
		Message:  input.Message,
		Category: "app",
	}
	if input.Subtitle != nil {
		req.Subtitle = *input.Subtitle
	}
	if input.Type != nil {
		req.Type = *input.Type
	}
	if input.Category != nil {
		req.Category = *input.Category
	}
	if input.Icon != nil {
		req.Icon = *input.Icon
	}
	if input.Language != nil {
		req.Language = *input.Language
	}
	if input.ActionURL != nil {
		req.ActionURL = *input.ActionURL
	}
	if input.ImageURL != nil {
		req.ImageURL = *input.ImageURL
	}
	if input.Priority != nil {
		req.Priority = *input.Priority
	}
	if input.SendPush != nil {
		req.SendPush = *input.SendPush
	}
	resp, err := r.AdminCreateNotificationUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return notificationRespToPayload(resp, false), nil
}

// AdminClearAllNotifications is the resolver for the adminClearAllNotifications field.
func (r *mutationResolver) AdminClearAllNotifications(ctx context.Context) (bool, error) {
	err := r.AdminClearAllNotificationsUC.Execute(ctx)
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminDeleteNotification is the resolver for the adminDeleteNotification field.
func (r *mutationResolver) AdminDeleteNotification(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.AdminDeleteNotificationUC.Execute(ctx, id)
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminUpdateNotification is the resolver for the adminUpdateNotification field.
func (r *mutationResolver) AdminUpdateNotification(ctx context.Context, id uuid.UUID, input model.UpdateNotificationInput) (*model.NotificationPayload, error) {
	req := &notificationUC.AdminUpdateNotificationRequest{
		Title:     input.Title,
		Subtitle:  input.Subtitle,
		Message:   input.Message,
		Type:      input.Type,
		Category:  input.Category,
		Icon:      input.Icon,
		Language:  input.Language,
		ActionURL: input.ActionURL,
		ImageURL:  input.ImageURL,
		Priority:  input.Priority,
	}
	n, err := r.AdminUpdateNotificationUC.Execute(ctx, id, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return domainNotificationToPayload(n), nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, language *string, limit *int) ([]*model.NotificationPayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	userIDStr := ""
	if userID != uuid.Nil {
		userIDStr = userID.String()
	}
	lang := ""
	if language != nil {
		lang = *language
	}
	l := 100
	if limit != nil && *limit > 0 {
		l = *limit
	}
	resp, err := r.ListNotificationsUC.Execute(ctx, &notificationDTO.ListNotificationsRequest{
		UserID:   userIDStr,
		Language: lang,
		Limit:    l,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	result := make([]*model.NotificationPayload, 0, len(resp))
	for _, n := range resp {
		result = append(result, notificationWithReadToPayload(n))
	}
	return result, nil
}
