package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric/masterfabric_go_basic/internal/application/organization/dto"
	organizationUC "github.com/masterfabric/masterfabric_go_basic/internal/application/organization/usecase"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrganizationInput) (*model.Organization, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	req := &dto.CreateOrganizationRequest{
		OwnerUserID: userID.String(),
		Name:        input.Name,
	}

	resp, err := r.CreateOrganizationUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return orgRespToModel(resp), nil
}

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, input model.UpdateOrganizationInput) (*model.Organization, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	resp, err := r.UpdateOrganizationUC.Execute(ctx, &dto.UpdateOrganizationRequest{
		OrganizationID: input.OrganizationID.String(),
		ActorUserID:    userID.String(),
		Name:           input.Name,
		Description:    input.Description,
		LogoURL:        input.LogoURL,
		WebsiteURL:     input.WebsiteURL,
		ContactEmail:   input.ContactEmail,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return orgRespToModel(resp), nil
}

// RemoveOrganizationMember is the resolver for the removeOrganizationMember field.
func (r *mutationResolver) RemoveOrganizationMember(ctx context.Context, organizationID uuid.UUID, userID uuid.UUID) (bool, error) {
	actorID := middleware.UserIDFromContext(ctx)
	if actorID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.RemoveOrganizationMemberUC.Execute(ctx, organizationID, actorID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// LeaveOrganization is the resolver for the leaveOrganization field.
func (r *mutationResolver) LeaveOrganization(ctx context.Context, organizationID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.LeaveOrganizationUC.Execute(ctx, organizationID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// SetOrganizationMemberSuspended is the resolver for the setOrganizationMemberSuspended field.
func (r *mutationResolver) SetOrganizationMemberSuspended(ctx context.Context, organizationID uuid.UUID, userID uuid.UUID, suspended bool) (bool, error) {
	actorID := middleware.UserIDFromContext(ctx)
	if actorID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.SetOrganizationMemberSuspendedUC.Execute(ctx, organizationID, actorID, userID, suspended); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// InviteToOrganization is the resolver for the inviteToOrganization field.
func (r *mutationResolver) InviteToOrganization(ctx context.Context, input model.InviteToOrganizationInput) (*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	req := &dto.InviteToOrganizationRequest{
		OrganizationID: input.OrganizationID.String(),
		InviterID:      userID.String(),
		InviteeEmail:   input.InviteeEmail,
	}

	resp, err := r.InviteToOrganizationUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return orgInvitationRespToModel(resp), nil
}

// AcceptInvitation is the resolver for the acceptInvitation field.
func (r *mutationResolver) AcceptInvitation(ctx context.Context, invitationID uuid.UUID) (*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	profile, err := r.GetProfileUC.Execute(ctx, userID.String())
	if err != nil || profile == nil {
		return nil, domainErr.New("UNAUTHENTICATED", "user profile not found", nil)
	}

	req := &dto.AcceptInvitationRequest{
		InvitationID: invitationID.String(),
		UserID:       userID.String(),
		UserEmail:    profile.Email,
	}

	resp, err := r.AcceptInvitationUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return orgInvitationRespToModel(resp), nil
}

// DeclineInvitation is the resolver for the declineInvitation field.
func (r *mutationResolver) DeclineInvitation(ctx context.Context, invitationID uuid.UUID) (*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	profile, err := r.GetProfileUC.Execute(ctx, userID.String())
	if err != nil || profile == nil {
		return nil, domainErr.New("UNAUTHENTICATED", "user profile not found", nil)
	}

	req := &dto.DeclineInvitationRequest{
		InvitationID: invitationID.String(),
		UserID:       userID.String(),
		UserEmail:    profile.Email,
	}

	resp, err := r.DeclineInvitationUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return orgInvitationRespToModel(resp), nil
}

// RevokeOrganizationInvitation is the resolver for the revokeOrganizationInvitation field.
func (r *mutationResolver) RevokeOrganizationInvitation(ctx context.Context, invitationID uuid.UUID) (*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.RevokeOrganizationInvitationUC.Execute(ctx, invitationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgInvitationRespToModel(resp), nil
}

// ResendOrganizationInvitation is the resolver for the resendOrganizationInvitation field.
func (r *mutationResolver) ResendOrganizationInvitation(ctx context.Context, invitationID uuid.UUID) (*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.ResendOrganizationInvitationUC.Execute(ctx, invitationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgInvitationRespToModel(resp), nil
}

// CreateOrganizationNews is the resolver for the createOrganizationNews field.
func (r *mutationResolver) CreateOrganizationNews(ctx context.Context, input model.CreateOrganizationNewsInput) (*model.OrganizationNews, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	img := ""
	if input.ImageURL != nil {
		img = *input.ImageURL
	}
	resp, err := r.CreateOrganizationNewsUC.Execute(ctx, &dto.CreateOrganizationNewsRequest{
		OrganizationID: input.OrganizationID.String(),
		ActorUserID:    userID.String(),
		Title:          input.Title,
		Description:    desc,
		ImageURL:       img,
		RichMetadata:   input.RichMetadata,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return orgNewsRespToModel(resp), nil
}

// UpdateOrganizationNews is the resolver for the updateOrganizationNews field.
func (r *mutationResolver) UpdateOrganizationNews(ctx context.Context, input model.UpdateOrganizationNewsInput) (*model.OrganizationNews, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.UpdateOrganizationNewsUC.Execute(ctx, &dto.UpdateOrganizationNewsRequest{
		NewsID:       input.NewsID.String(),
		ActorUserID:  userID.String(),
		Title:        input.Title,
		Description:  input.Description,
		ImageURL:     input.ImageURL,
		RichMetadata: input.RichMetadata,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return orgNewsRespToModel(resp), nil
}

// DeleteOrganizationNews is the resolver for the deleteOrganizationNews field.
func (r *mutationResolver) DeleteOrganizationNews(ctx context.Context, newsID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteOrganizationNewsUC.Execute(ctx, newsID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// PostOrganizationMessage is the resolver for the postOrganizationMessage field.
func (r *mutationResolver) PostOrganizationMessage(ctx context.Context, organizationID uuid.UUID, body string) (*model.OrganizationMessage, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.PostOrganizationMessageUC.Execute(ctx, &dto.PostOrganizationMessageRequest{
		OrganizationID: organizationID.String(),
		ActorUserID:    userID.String(),
		Body:           body,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	gqlMsg := orgMessageDTOToModel(resp)
	r.OrganizationMessageBroadcaster.Broadcast(organizationID, gqlMsg)
	return gqlMsg, nil
}

// DeleteOrganizationMessage is the resolver for the deleteOrganizationMessage field.
func (r *mutationResolver) DeleteOrganizationMessage(ctx context.Context, organizationID uuid.UUID, messageID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteOrganizationMessageUC.Execute(ctx, organizationID, messageID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// MyOrganizations is the resolver for the myOrganizations field.
func (r *queryResolver) MyOrganizations(ctx context.Context) ([]*model.Organization, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	orgs, err := r.ListOrganizationsUC.Execute(ctx, userID)
	if err != nil {
		return nil, mapErr(err)
	}

	result := make([]*model.Organization, 0, len(orgs))
	for _, o := range orgs {
		result = append(result, orgRespToModel(o))
	}
	return result, nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, organizationID uuid.UUID) (*model.Organization, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.GetOrganizationUC.Execute(ctx, organizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgRespToModel(resp), nil
}

// MyPendingInvitations is the resolver for the myPendingInvitations field.
func (r *queryResolver) MyPendingInvitations(ctx context.Context) ([]*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	profile, err := r.GetProfileUC.Execute(ctx, userID.String())
	if err != nil || profile == nil {
		return nil, domainErr.New("UNAUTHENTICATED", "user profile not found", nil)
	}

	invitations, err := r.ListPendingInvitationsUC.Execute(ctx, profile.Email)
	if err != nil {
		return nil, mapErr(err)
	}

	result := make([]*model.OrganizationInvitation, 0, len(invitations))
	for _, inv := range invitations {
		result = append(result, orgInvitationRespToModel(inv))
	}
	return result, nil
}

// OrganizationMembers is the resolver for the organizationMembers field.
func (r *queryResolver) OrganizationMembers(ctx context.Context, orgID uuid.UUID) ([]*model.OrganizationMember, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	members, err := r.ListOrganizationMembersUC.Execute(ctx, orgID, userID)
	if err != nil {
		return nil, mapErr(err)
	}

	result := make([]*model.OrganizationMember, 0, len(members))
	for _, m := range members {
		result = append(result, orgMemberRespToModel(m))
	}
	return result, nil
}

// OrganizationInvitations is the resolver for the organizationInvitations field.
func (r *queryResolver) OrganizationInvitations(ctx context.Context, orgID uuid.UUID) ([]*model.OrganizationInvitation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	invitations, err := r.ListOrganizationInvitationsUC.Execute(ctx, &organizationUC.ListOrganizationInvitationsRequest{
		OrganizationID: orgID.String(),
		UserID:         userID.String(),
	})
	if err != nil {
		return nil, mapErr(err)
	}

	result := make([]*model.OrganizationInvitation, 0, len(invitations))
	for _, inv := range invitations {
		result = append(result, orgInvitationRespToModel(inv))
	}
	return result, nil
}

// OrganizationNews is the resolver for the organizationNews field.
func (r *queryResolver) OrganizationNews(ctx context.Context, organizationID uuid.UUID, limit *int, before *time.Time) ([]*model.OrganizationNews, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	lim := 50
	if limit != nil && *limit > 0 && *limit <= 200 {
		lim = *limit
	}
	items, err := r.ListOrganizationNewsUC.Execute(ctx, organizationID, userID, lim, before)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationNews, 0, len(items))
	for _, it := range items {
		out = append(out, orgNewsRespToModel(it))
	}
	return out, nil
}

// OrganizationMessages is the resolver for the organizationMessages field.
func (r *queryResolver) OrganizationMessages(ctx context.Context, organizationID uuid.UUID, limit *int, before *time.Time) ([]*model.OrganizationMessage, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	lim := 50
	if limit != nil && *limit > 0 && *limit <= 200 {
		lim = *limit
	}
	items, err := r.ListOrganizationMessagesUC.Execute(ctx, organizationID, userID, lim, before)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationMessage, 0, len(items))
	for _, it := range items {
		out = append(out, orgMessageDTOToModel(it))
	}
	return out, nil
}

// OrganizationMessageCreated is the resolver for the organizationMessageCreated field.
func (r *subscriptionResolver) OrganizationMessageCreated(ctx context.Context, organizationID uuid.UUID) (<-chan *model.OrganizationMessage, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}
	if _, err := r.GetOrganizationUC.Execute(ctx, organizationID, userID); err != nil {
		return nil, mapErr(err)
	}
	slog.Info("graphql subscription start", slog.String("subscription", "organizationMessageCreated"), slog.String("organization_id", organizationID.String()), slog.String("user_id", userID.String()))
	ch := r.OrganizationMessageBroadcaster.Subscribe(organizationID)
	go func() {
		<-ctx.Done()
		slog.Info("graphql subscription end", slog.String("subscription", "organizationMessageCreated"), slog.String("organization_id", organizationID.String()))
		r.OrganizationMessageBroadcaster.Unsubscribe(organizationID, ch)
	}()
	return ch, nil
}
