package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	"github.com/masterfabric/masterfabric_go_basic/internal/application/organization/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// OrganizationOwnerTodoDashboard is the resolver for the organizationOwnerTodoDashboard field.
func (r *queryResolver) OrganizationOwnerTodoDashboard(ctx context.Context, input model.OrganizationOwnerTodoDashboardInput) (*model.OrganizationOwnerTodoDashboard, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	var pids []string
	for _, id := range input.ProjectIds {
		pids = append(pids, id.String())
	}

	week := input.Period == model.OrganizationOwnerDashboardPeriodWeek
	resp, err := r.OwnerTodoDashboardUC.Execute(ctx, &dto.OwnerTodoDashboardRequest{
		OrganizationID:  input.OrganizationID.String(),
		ActorUserID:     userID.String(),
		PeriodWeek:      week,
		PeriodOffset:    input.PeriodOffset,
		IncludeSubtasks: input.IncludeSubtasks,
		ProjectIDs:      pids,
	})
	if err != nil {
		return nil, mapErr(err)
	}

	per := model.OrganizationOwnerDashboardPeriodMonth
	if week {
		per = model.OrganizationOwnerDashboardPeriodWeek
	}

	daily := make([]*model.OrganizationOwnerDashboardDayBucket, 0, len(resp.Daily))
	for _, d := range resp.Daily {
		day := d.Day
		daily = append(daily, &model.OrganizationOwnerDashboardDayBucket{
			Day:            day,
			CompletedCount: d.CompletedCount,
		})
	}

	d2 := make([]*model.OrganizationOwnerProjectDoneInPeriod, 0, len(resp.Donut2))
	for _, p := range resp.Donut2 {
		d2 = append(d2, &model.OrganizationOwnerProjectDoneInPeriod{
			ProjectID:   p.ProjectID,
			ProjectName: p.ProjectName,
			IsGeneral:   p.IsGeneral,
			Count:       p.Count,
		})
	}

	oa := make([]*model.OrganizationOwnerAssigneeSlice, 0, len(resp.Assignee))
	for _, a := range resp.Assignee {
		var nn *string
		if a.Nickname != "" {
			s := a.Nickname
			nn = &s
		}
		oa = append(oa, &model.OrganizationOwnerAssigneeSlice{
			UserID:    a.UserID,
			Nickname:  nn,
			OpenCount: a.OpenCount,
		})
	}

	return &model.OrganizationOwnerTodoDashboard{
		OrganizationID:            input.OrganizationID,
		Period:                    per,
		IncludeSubtasks:           resp.IncludeSubtasks,
		PeriodStart:               resp.PeriodStart,
		PeriodEnd:                 resp.PeriodEnd,
		PreviousPeriodStart:       resp.PreviousPeriodStart,
		PreviousPeriodEnd:         resp.PreviousPeriodEnd,
		OpenCount:                 resp.OpenCount,
		DoneCount:                 resp.DoneCount,
		CompletedInSelectedPeriod: resp.CompletedInSelected,
		CompletedInPreviousPeriod: resp.CompletedInPrevious,
		DailySeries:               daily,
		DonutOpenCount:            resp.OpenCount,
		DonutDoneCount:            resp.DoneCount,
		DoneInPeriodByProject:     d2,
		OpenByAssignee:            oa,
	}, nil
}
