package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/generated"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// CreateOrganizationProject is the resolver for the createOrganizationProject field.
func (r *mutationResolver) CreateOrganizationProject(ctx context.Context, input model.CreateOrganizationProjectInput) (*model.OrganizationProject, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	resp, err := r.CreateOrganizationProjectUC.Execute(ctx, input.OrganizationID, userID, input.Name, desc)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectRespToModel(resp), nil
}

// UpdateOrganizationProject is the resolver for the updateOrganizationProject field.
func (r *mutationResolver) UpdateOrganizationProject(ctx context.Context, input model.UpdateOrganizationProjectInput) (*model.OrganizationProject, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.UpdateOrganizationProjectUC.Execute(ctx, input.ProjectID, userID, input.Name, input.Description)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectRespToModel(resp), nil
}

// DeleteOrganizationProject is the resolver for the deleteOrganizationProject field.
func (r *mutationResolver) DeleteOrganizationProject(ctx context.Context, projectID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteOrganizationProjectUC.Execute(ctx, projectID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// ArchiveOrganizationProject is the resolver for the archiveOrganizationProject field.
func (r *mutationResolver) ArchiveOrganizationProject(ctx context.Context, projectID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.ArchiveOrganizationProjectUC.Execute(ctx, projectID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// UnarchiveOrganizationProject is the resolver for the unarchiveOrganizationProject field.
func (r *mutationResolver) UnarchiveOrganizationProject(ctx context.Context, projectID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.UnarchiveOrganizationProjectUC.Execute(ctx, projectID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AddOrganizationProjectMember is the resolver for the addOrganizationProjectMember field.
func (r *mutationResolver) AddOrganizationProjectMember(ctx context.Context, projectID uuid.UUID, userID uuid.UUID) (bool, error) {
	actorID := middleware.UserIDFromContext(ctx)
	if actorID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.AddOrganizationProjectMemberUC.Execute(ctx, projectID, actorID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// RemoveOrganizationProjectMember is the resolver for the removeOrganizationProjectMember field.
func (r *mutationResolver) RemoveOrganizationProjectMember(ctx context.Context, projectID uuid.UUID, userID uuid.UUID) (bool, error) {
	actorID := middleware.UserIDFromContext(ctx)
	if actorID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.RemoveOrganizationProjectMemberUC.Execute(ctx, projectID, actorID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// CreateOrganizationProjectTodo is the resolver for the createOrganizationProjectTodo field.
func (r *mutationResolver) CreateOrganizationProjectTodo(ctx context.Context, input model.CreateOrganizationProjectTodoInput) (*model.OrganizationProjectTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	var dueAt *string
	if input.DueAt != nil {
		s := input.DueAt.UTC().Format(time.RFC3339)
		dueAt = &s
	}
	resp, err := r.CreateOrganizationProjectTodoUC.Execute(ctx, input.ProjectID, userID, input.Title, input.AssignedToUserID, dueAt)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectTodoRespToModel(resp), nil
}

// UpdateOrganizationProjectTodo is the resolver for the updateOrganizationProjectTodo field.
func (r *mutationResolver) UpdateOrganizationProjectTodo(ctx context.Context, input model.UpdateOrganizationProjectTodoInput) (*model.OrganizationProjectTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	var st *string
	if input.Status != nil {
		s := string(*input.Status)
		st = &s
	}
	var dueAt *string
	if input.DueAt != nil {
		s := input.DueAt.UTC().Format(time.RFC3339)
		dueAt = &s
	}
	resp, err := r.UpdateOrganizationProjectTodoUC.Execute(ctx, input.TodoID, userID, input.Title, st, dueAt, input.ClearDueAt)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectTodoRespToModel(resp), nil
}

// DeleteOrganizationProjectTodo is the resolver for the deleteOrganizationProjectTodo field.
func (r *mutationResolver) DeleteOrganizationProjectTodo(ctx context.Context, todoID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteOrganizationProjectTodoUC.Execute(ctx, todoID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// ArchiveOrganizationProjectTodo is the resolver for the archiveOrganizationProjectTodo field.
func (r *mutationResolver) ArchiveOrganizationProjectTodo(ctx context.Context, todoID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.ArchiveOrganizationProjectTodoUC.Execute(ctx, todoID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// UnarchiveOrganizationProjectTodo is the resolver for the unarchiveOrganizationProjectTodo field.
func (r *mutationResolver) UnarchiveOrganizationProjectTodo(ctx context.Context, todoID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.UnarchiveOrganizationProjectTodoUC.Execute(ctx, todoID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// CreateOrganizationProjectTodoSubtask is the resolver for the createOrganizationProjectTodoSubtask field.
func (r *mutationResolver) CreateOrganizationProjectTodoSubtask(ctx context.Context, input model.CreateOrganizationProjectTodoSubtaskInput) (*model.OrganizationProjectTodoSubtask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.CreateOrganizationProjectTodoSubtaskUC.Execute(ctx, input.ProjectTodoID, userID, input.Title, input.Completed)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectTodoSubtaskDomainToModel(row), nil
}

// UpdateOrganizationProjectTodoSubtask is the resolver for the updateOrganizationProjectTodoSubtask field.
func (r *mutationResolver) UpdateOrganizationProjectTodoSubtask(ctx context.Context, input model.UpdateOrganizationProjectTodoSubtaskInput) (*model.OrganizationProjectTodoSubtask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.UpdateOrganizationProjectTodoSubtaskUC.Execute(ctx, input.ID, userID, input.Title, input.Completed)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectTodoSubtaskDomainToModel(row), nil
}

// DeleteOrganizationProjectTodoSubtask is the resolver for the deleteOrganizationProjectTodoSubtask field.
func (r *mutationResolver) DeleteOrganizationProjectTodoSubtask(ctx context.Context, id uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteOrganizationProjectTodoSubtaskUC.Execute(ctx, id, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// CreateOrganizationProjectPurchase is the resolver for the createOrganizationProjectPurchase field.
func (r *mutationResolver) CreateOrganizationProjectPurchase(ctx context.Context, input model.CreateOrganizationProjectPurchaseInput) (*model.OrganizationProjectPurchase, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	tax := 0.0
	if input.TaxRate != nil {
		tax = *input.TaxRate
	}
	qty := 1.0
	if input.Quantity != nil {
		qty = *input.Quantity
	}
	purpose := ""
	if input.ProductPurpose != nil {
		purpose = *input.ProductPurpose
	}
	ccy := ""
	if input.Currency != nil {
		ccy = *input.Currency
	}
	var st *string
	if input.Status != nil {
		s := string(*input.Status)
		st = &s
	}
	note := ""
	if input.StatusNote != nil {
		note = *input.StatusNote
	}
	resp, err := r.CreateOrganizationProjectPurchaseUC.Execute(ctx, input.ProjectID, userID, input.ProductName, tax, input.Price, qty, purpose, input.ProductLink, ccy, st, note)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectPurchaseRespToModel(resp), nil
}

// UpdateOrganizationProjectPurchase is the resolver for the updateOrganizationProjectPurchase field.
func (r *mutationResolver) UpdateOrganizationProjectPurchase(ctx context.Context, input model.UpdateOrganizationProjectPurchaseInput) (*model.OrganizationProjectPurchase, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	var st *string
	if input.Status != nil {
		s := string(*input.Status)
		st = &s
	}
	resp, err := r.UpdateOrganizationProjectPurchaseUC.Execute(ctx, input.PurchaseID, userID,
		input.ProductName,
		input.TaxRate,
		input.ProductPurpose,
		input.Price,
		input.Quantity,
		input.ProductLink,
		input.ClearProductLink,
		st,
		input.StatusNote,
		input.Currency,
	)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectPurchaseRespToModel(resp), nil
}

// DeleteOrganizationProjectPurchase is the resolver for the deleteOrganizationProjectPurchase field.
func (r *mutationResolver) DeleteOrganizationProjectPurchase(ctx context.Context, purchaseID uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteOrganizationProjectPurchaseUC.Execute(ctx, purchaseID, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// CreateOrganizationProjectOrgInvite is the resolver for the createOrganizationProjectOrgInvite field.
func (r *mutationResolver) CreateOrganizationProjectOrgInvite(ctx context.Context, input model.CreateOrganizationProjectOrgInviteInput) (*model.OrganizationProjectOrgParticipation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.CreateOrganizationProjectOrgInviteUC.Execute(ctx, input.ProjectID, input.ParticipantOrganizationID, userID, input.CapabilitiesJSON)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectOrgParticipationDomainToModel(row), nil
}

// AcceptOrganizationProjectOrgInvite is the resolver for the acceptOrganizationProjectOrgInvite field.
func (r *mutationResolver) AcceptOrganizationProjectOrgInvite(ctx context.Context, projectID uuid.UUID, participantOrganizationID uuid.UUID) (*model.OrganizationProjectOrgParticipation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.AcceptOrganizationProjectOrgInviteUC.Execute(ctx, projectID, participantOrganizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectOrgParticipationDomainToModel(row), nil
}

// DeclineOrganizationProjectOrgInvite is the resolver for the declineOrganizationProjectOrgInvite field.
func (r *mutationResolver) DeclineOrganizationProjectOrgInvite(ctx context.Context, projectID uuid.UUID, participantOrganizationID uuid.UUID) (*model.OrganizationProjectOrgParticipation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.DeclineOrganizationProjectOrgInviteUC.Execute(ctx, projectID, participantOrganizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectOrgParticipationDomainToModel(row), nil
}

// UpdateOrganizationProjectOrgParticipationCapabilities is the resolver for the updateOrganizationProjectOrgParticipationCapabilities field.
func (r *mutationResolver) UpdateOrganizationProjectOrgParticipationCapabilities(ctx context.Context, projectID uuid.UUID, participantOrganizationID uuid.UUID, capabilitiesJSON *string) (*model.OrganizationProjectOrgParticipation, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.UpdateOrganizationProjectOrgParticipationCapabilitiesUC.Execute(ctx, projectID, participantOrganizationID, userID, capabilitiesJSON)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectOrgParticipationDomainToModel(row), nil
}

// TransferOrganizationProjectOwnership is the resolver for the transferOrganizationProjectOwnership field.
func (r *mutationResolver) TransferOrganizationProjectOwnership(ctx context.Context, projectID uuid.UUID, newHostOrganizationID uuid.UUID) (*model.OrganizationProject, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.TransferOrganizationProjectOwnershipUC.Execute(ctx, projectID, newHostOrganizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectRespToModel(resp), nil
}

// Subtasks is the resolver for the subtasks field.
func (r *organizationProjectTodoResolver) Subtasks(ctx context.Context, obj *model.OrganizationProjectTodo) ([]*model.OrganizationProjectTodoSubtask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListOrganizationProjectTodoSubtasksUC.Execute(ctx, obj.ID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectTodoSubtask, 0, len(rows))
	for _, s := range rows {
		out = append(out, orgProjectTodoSubtaskDomainToModel(s))
	}
	return out, nil
}

// OrganizationProjects is the resolver for the organizationProjects field.
func (r *queryResolver) OrganizationProjects(ctx context.Context, organizationID uuid.UUID) ([]*model.OrganizationProject, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListOrganizationProjectsUC.Execute(ctx, organizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProject, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectRespToModel(row))
	}
	return out, nil
}

// ArchivedOrganizationProjects is the resolver for the archivedOrganizationProjects field.
func (r *queryResolver) ArchivedOrganizationProjects(ctx context.Context, organizationID uuid.UUID) ([]*model.OrganizationProject, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListArchivedOrganizationProjectsUC.Execute(ctx, organizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProject, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectRespToModel(row))
	}
	return out, nil
}

// OrganizationProject is the resolver for the organizationProject field.
func (r *queryResolver) OrganizationProject(ctx context.Context, projectID uuid.UUID) (*model.OrganizationProject, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	resp, err := r.GetOrganizationProjectUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return orgProjectRespToModel(resp), nil
}

// OrganizationProjectMembers is the resolver for the organizationProjectMembers field.
func (r *queryResolver) OrganizationProjectMembers(ctx context.Context, projectID uuid.UUID) ([]*model.OrganizationProjectMember, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListOrganizationProjectMembersUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectMember, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectMemberRespToModel(row))
	}
	return out, nil
}

// OrganizationProjectTodos is the resolver for the organizationProjectTodos field.
func (r *queryResolver) OrganizationProjectTodos(ctx context.Context, projectID uuid.UUID) ([]*model.OrganizationProjectTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListOrganizationProjectTodosUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectTodo, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectTodoRespToModel(row))
	}
	return out, nil
}

// ArchivedOrganizationProjectTodos is the resolver for the archivedOrganizationProjectTodos field.
func (r *queryResolver) ArchivedOrganizationProjectTodos(ctx context.Context, projectID uuid.UUID) ([]*model.OrganizationProjectTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListArchivedOrganizationProjectTodosUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectTodo, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectTodoRespToModel(row))
	}
	return out, nil
}

// OrganizationProjectPurchases is the resolver for the organizationProjectPurchases field.
func (r *queryResolver) OrganizationProjectPurchases(ctx context.Context, projectID uuid.UUID) ([]*model.OrganizationProjectPurchase, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListOrganizationProjectPurchasesUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectPurchase, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectPurchaseRespToModel(row))
	}
	return out, nil
}

// OrganizationProjectMyCapabilities is the resolver for the organizationProjectMyCapabilities field.
func (r *queryResolver) OrganizationProjectMyCapabilities(ctx context.Context, projectID uuid.UUID) (*model.OrganizationProjectMyCapabilities, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	caps, err := r.GetOrganizationProjectMyCapabilitiesUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	return &model.OrganizationProjectMyCapabilities{
		CanEditTodos:     caps.CanEditTodos,
		CanEditPurchases: caps.CanEditPurchases,
	}, nil
}

// PendingOrganizationProjectOrgInvites is the resolver for the pendingOrganizationProjectOrgInvites field.
func (r *queryResolver) PendingOrganizationProjectOrgInvites(ctx context.Context, organizationID uuid.UUID) ([]*model.OrganizationProjectOrgInvitePendingRow, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListPendingOrganizationProjectOrgInvitesUC.Execute(ctx, organizationID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectOrgInvitePendingRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectOrgInvitePendingRowToModel(row))
	}
	return out, nil
}

// OrganizationProjectOrgParticipations is the resolver for the organizationProjectOrgParticipations field.
func (r *queryResolver) OrganizationProjectOrgParticipations(ctx context.Context, projectID uuid.UUID) ([]*model.OrganizationProjectOrgParticipationRow, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListOrganizationProjectOrgParticipationsUC.Execute(ctx, projectID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.OrganizationProjectOrgParticipationRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, orgProjectOrgParticipationRowToModel(row))
	}
	return out, nil
}

// OrganizationProjectTodo returns generated.OrganizationProjectTodoResolver implementation.
func (r *Resolver) OrganizationProjectTodo() generated.OrganizationProjectTodoResolver {
	return &organizationProjectTodoResolver{r}
}

type organizationProjectTodoResolver struct{ *Resolver }
