package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	otpDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/otp/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/domain/iam/policy"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// RequestOtp is the resolver for the requestOTP field.
func (r *mutationResolver) RequestOtp(ctx context.Context, input model.RequestOTPInput) (*model.OTPRequestPayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	resp, err := r.RequestOTPUC.Execute(ctx, &otpDTO.RequestOTPRequest{
		UserID:  userID.String(),
		Purpose: gqlOTPPurposeToString(input.Purpose),
	})
	if err != nil {
		return nil, mapErr(err)
	}

	otpID, _ := uuid.Parse(resp.OTPID)
	return &model.OTPRequestPayload{
		OtpID:     otpID,
		Channel:   gqlOTPChannel(resp.Channel),
		ExpiresAt: resp.ExpiresAt,
	}, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, input model.VerifyOTPInput) (*model.OTPVerifyPayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	resp, err := r.VerifyOTPUC.Execute(ctx, &otpDTO.VerifyOTPRequest{
		UserID:  userID.String(),
		Code:    input.Code,
		Purpose: gqlOTPPurposeToString(input.Purpose),
	})
	if err != nil {
		return nil, mapErr(err)
	}

	otpID, _ := uuid.Parse(resp.OTPID)
	return &model.OTPVerifyPayload{
		Verified: resp.Verified,
		OtpID:    otpID,
	}, nil
}

// AdminRequestOtp is the resolver for the adminRequestOTP field.
func (r *mutationResolver) AdminRequestOtp(ctx context.Context, input model.AdminRequestOTPInput) (*model.OTPRequestPayload, error) {
	if err := policy.RequireAdmin(ctx); err != nil {
		return nil, mapErr(err)
	}
	resp, err := r.RequestOTPUC.Execute(ctx, &otpDTO.RequestOTPRequest{
		UserID:  input.UserID.String(),
		Purpose: gqlOTPPurposeToString(input.Purpose),
	})
	if err != nil {
		return nil, mapErr(err)
	}

	otpID, _ := uuid.Parse(resp.OTPID)
	return &model.OTPRequestPayload{
		OtpID:     otpID,
		Channel:   gqlOTPChannel(resp.Channel),
		ExpiresAt: resp.ExpiresAt,
	}, nil
}

// AdminPendingOTPs is the resolver for the adminPendingOTPs field.
func (r *queryResolver) AdminPendingOTPs(ctx context.Context, limit *int, offset *int) ([]*model.AdminOTPEntry, error) {
	l, o := 50, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	otps, err := r.AdminListPendingOTPsUC.Execute(ctx, l, o)
	if err != nil {
		return nil, mapErr(err)
	}
	return adminOTPsToModel(otps), nil
}

// AdminUserOTPHistory is the resolver for the adminUserOTPHistory field.
func (r *queryResolver) AdminUserOTPHistory(ctx context.Context, userID uuid.UUID, limit *int, offset *int) ([]*model.AdminOTPEntry, error) {
	l, o := 50, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	otps, err := r.AdminUserOTPHistoryUC.Execute(ctx, userID, l, o)
	if err != nil {
		return nil, mapErr(err)
	}
	return adminOTPsToModel(otps), nil
}
