package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	prdto "github.com/masterfabric/masterfabric_go_basic/internal/application/productrelease/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
)

// AdminUpdateProductRelease is the resolver for the adminUpdateProductRelease field.
func (r *mutationResolver) AdminUpdateProductRelease(ctx context.Context, input model.AdminProductReleaseInput) (*model.ProductRelease, error) {
	resp, err := r.AdminUpdateProductReleaseUC.Execute(ctx, &prdto.AdminUpdateProductReleaseRequest{
		Version:           input.Version,
		ChangelogMarkdown: input.ChangelogMarkdown,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return productReleaseToModel(resp), nil
}

// ProductRelease is the resolver for the productRelease field.
func (r *queryResolver) ProductRelease(ctx context.Context) (*model.ProductRelease, error) {
	resp, err := r.GetProductReleaseUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	return productReleaseToModel(resp), nil
}
