package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric/masterfabric_go_basic/internal/application/todos/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/generated"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.UserTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	completed := false
	if input.Completed != nil {
		completed = *input.Completed
	}

	req := &dto.CreateTodoRequest{
		UserID:           userID.String(),
		Title:            input.Title,
		Completed:        completed,
		OrganizationID:   uuidPtrToStr(input.OrganizationID),
		AssignedToUserID: uuidPtrToStr(input.AssignedToUserID),
	}
	if input.DueAt != nil {
		s := input.DueAt.UTC().Format(time.RFC3339)
		req.DueAt = &s
	}

	resp, err := r.CreateTodoUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return todoRespToModel(resp), nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input model.UpdateTodoInput) (*model.UserTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	req := &dto.UpdateTodoRequest{
		UserID:            userID.String(),
		ID:                input.ID.String(),
		Title:             input.Title,
		OrganizationID:    uuidPtrToStr(input.OrganizationID),
		ClearOrganization: input.ClearOrganization,
		AssignedToUserID:  uuidPtrToStr(input.AssignedToUserID),
		ClearDueAt:        input.ClearDueAt,
	}
	if input.Completed != nil {
		req.Completed = input.Completed
	}
	if input.DueAt != nil {
		s := input.DueAt.UTC().Format(time.RFC3339)
		req.DueAt = &s
	}

	resp, err := r.UpdateTodoUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}

	return todoRespToModel(resp), nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	req := &dto.DeleteTodoRequest{
		UserID: userID.String(),
		ID:     id.String(),
	}

	if err := r.DeleteTodoUC.Execute(ctx, req); err != nil {
		return false, mapErr(err)
	}

	return true, nil
}

// CreateUserTodoSubtask is the resolver for the createUserTodoSubtask field.
func (r *mutationResolver) CreateUserTodoSubtask(ctx context.Context, input model.CreateUserTodoSubtaskInput) (*model.UserTodoSubtask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.CreateUserTodoSubtaskUC.Execute(ctx, input.UserTodoID, userID, input.Title, input.Completed)
	if err != nil {
		return nil, mapErr(err)
	}
	return userTodoSubtaskDomainToModel(row), nil
}

// UpdateUserTodoSubtask is the resolver for the updateUserTodoSubtask field.
func (r *mutationResolver) UpdateUserTodoSubtask(ctx context.Context, input model.UpdateUserTodoSubtaskInput) (*model.UserTodoSubtask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	row, err := r.UpdateUserTodoSubtaskUC.Execute(ctx, input.ID, userID, input.Title, input.Completed)
	if err != nil {
		return nil, mapErr(err)
	}
	return userTodoSubtaskDomainToModel(row), nil
}

// DeleteUserTodoSubtask is the resolver for the deleteUserTodoSubtask field.
func (r *mutationResolver) DeleteUserTodoSubtask(ctx context.Context, id uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	if err := r.DeleteUserTodoSubtaskUC.Execute(ctx, id, userID); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// MyTodos is the resolver for the myTodos field.
func (r *queryResolver) MyTodos(ctx context.Context) ([]*model.UserTodo, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}

	todos, err := r.ListTodosUC.Execute(ctx, userID)
	if err != nil {
		return nil, mapErr(err)
	}

	result := make([]*model.UserTodo, 0, len(todos))
	for _, t := range todos {
		result = append(result, todoRespToModel(t))
	}
	return result, nil
}

// Subtasks is the resolver for the subtasks field.
func (r *userTodoResolver) Subtasks(ctx context.Context, obj *model.UserTodo) ([]*model.UserTodoSubtask, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.New("UNAUTHENTICATED", "authentication required", nil)
	}
	rows, err := r.ListUserTodoSubtasksUC.Execute(ctx, obj.ID, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.UserTodoSubtask, 0, len(rows))
	for _, s := range rows {
		out = append(out, userTodoSubtaskDomainToModel(s))
	}
	return out, nil
}

// UserTodo returns generated.UserTodoResolver implementation.
func (r *Resolver) UserTodo() generated.UserTodoResolver { return &userTodoResolver{r} }

type userTodoResolver struct{ *Resolver }
