package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"strings"
	"time"

	"github.com/google/uuid"
	userDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/user/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/generated"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UserProfile, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	// Parse optional date-of-birth string (YYYY-MM-DD) into *time.Time
	var dob *time.Time
	if input.DateOfBirth != nil && *input.DateOfBirth != "" {
		t, err := time.Parse("2006-01-02", *input.DateOfBirth)
		if err != nil {
			return nil, domainErr.New("VALIDATION_ERROR", "dateOfBirth must be in YYYY-MM-DD format", nil)
		}
		dob = &t
	}

	// Convert Gender enum pointer → domain string pointer
	var genderStr *string
	if input.Gender != nil {
		s := genderToString(input.Gender)
		genderStr = &s
	}

	var emailPtr *string
	if input.Email != nil {
		s := strings.TrimSpace(*input.Email)
		if s != "" {
			emailPtr = &s
		}
	}

	var emailChangeOtp *string
	if input.EmailChangeOtpID != nil {
		s := input.EmailChangeOtpID.String()
		emailChangeOtp = &s
	}

	resp, err := r.UpdateProfileUC.Execute(ctx, &userDTO.UpdateProfileRequest{
		UserID:           userID.String(),
		Email:            emailPtr,
		EmailChangeOtpID: emailChangeOtp,
		DisplayName:      input.DisplayName,
		Nickname:         input.Nickname,
		AvatarURL:        input.AvatarURL,
		Bio:              input.Bio,
		PhoneNumber:      input.PhoneNumber,
		TelegramChatID:   input.TelegramChatID,
		DateOfBirth:      dob,
		Gender:           genderStr,
		Location:         input.Location,
		WebsiteURL:       input.WebsiteURL,
		SocialTwitter:    input.SocialTwitter,
		SocialGitHub:     input.SocialGitHub,
		SocialLinkedIn:   input.SocialLinkedIn,
		Language:         input.Language,
	})
	if err != nil {
		return nil, mapErr(err)
	}

	// Include the default address in the profile response
	defaultAddr, _ := r.GetDefaultAddressUC.Execute(ctx, userID.String())
	return profileRespToModel(resp, defaultAddr), nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.ErrUnauthorized
	}

	if err := r.DeleteAccountUC.Execute(ctx, userID.String()); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// UpsertAddress is the resolver for the upsertAddress field.
func (r *mutationResolver) UpsertAddress(ctx context.Context, input model.UpsertAddressInput) (*model.UserAddress, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	// Convert *uuid.UUID → *string for the DTO
	var addrIDStr *string
	if input.AddressID != nil {
		s := input.AddressID.String()
		addrIDStr = &s
	}

	resp, err := r.UpsertAddressUC.Execute(ctx, &userDTO.UpsertAddressRequest{
		UserID:       userID.String(),
		AddressID:    addrIDStr,
		Title:        input.Title,
		AddressLine1: input.AddressLine1,
		AddressLine2: input.AddressLine2,
		City:         input.City,
		State:        input.State,
		PostalCode:   input.PostalCode,
		Country:      input.Country,
		IsDefault:    input.IsDefault,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return addressRespToModel(resp), nil
}

// DeleteMyAddress is the resolver for the deleteMyAddress field.
func (r *mutationResolver) DeleteMyAddress(ctx context.Context, id uuid.UUID) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return false, domainErr.ErrUnauthorized
	}
	if err := r.DeleteAddressUC.Execute(ctx, userID.String(), id.String()); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.UserProfile, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	resp, err := r.GetProfileUC.Execute(ctx, userID.String())
	if err != nil {
		return nil, mapErr(err)
	}

	// Attach the default address (nil if none set — that's fine)
	defaultAddr, _ := r.GetDefaultAddressUC.Execute(ctx, userID.String())
	return profileRespToModel(resp, defaultAddr), nil
}

// MyAccountDeletionImpact is the resolver for the myAccountDeletionImpact field.
func (r *queryResolver) MyAccountDeletionImpact(ctx context.Context) (*model.MyAccountDeletionImpact, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}
	resp, err := r.GetMyAccountDeletionImpactUC.Execute(ctx, userID)
	if err != nil {
		return nil, mapErr(err)
	}
	owned := make([]*model.MyOwnedOrganizationDeletionImpact, 0, len(resp.OwnedOrganizations))
	for _, o := range resp.OwnedOrganizations {
		owned = append(owned, &model.MyOwnedOrganizationDeletionImpact{
			OrganizationID:   o.OrganizationID,
			Name:             o.Name,
			OtherMemberCount: o.OtherMemberCount,
		})
	}
	return &model.MyAccountDeletionImpact{
		OwnedTodoCount:                   resp.OwnedTodoCount,
		TodoAssigneeClearCount:           resp.TodoAssigneeClearCount,
		OrganizationMembershipCount:      resp.OrganizationMembershipCount,
		OwnedOrganizations:               owned,
		AddressCount:                     resp.AddressCount,
		DeviceCount:                      resp.DeviceCount,
		HasUserSettings:                  resp.HasUserSettings,
		NotificationReadCount:            resp.NotificationReadCount,
		SessionCount:                     resp.SessionCount,
		UserMessageCount:                 resp.UserMessageCount,
		PendingInvitationAsInviterCount:  resp.PendingInvitationAsInviterCount,
		OrganizationMessageAuthoredCount: resp.OrganizationMessageAuthoredCount,
		OrganizationNewsAuthoredCount:    resp.OrganizationNewsAuthoredCount,
		OtpCodeHistoryCount:              resp.OtpCodeHistoryCount,
	}, nil
}

// NicknameAvailable is the resolver for the nicknameAvailable field.
func (r *queryResolver) NicknameAvailable(ctx context.Context, nickname string) (bool, error) {
	var excludeUserID *string
	if userID := middleware.UserIDFromContext(ctx); userID != uuid.Nil {
		s := userID.String()
		excludeUserID = &s
	}
	return r.NicknameAvailableUC.Execute(ctx, nickname, excludeUserID)
}

// MyAddresses is the resolver for the myAddresses field.
func (r *queryResolver) MyAddresses(ctx context.Context) ([]*model.UserAddress, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	addrs, err := r.GetAddressUC.Execute(ctx, userID.String())
	if err != nil {
		return nil, mapErr(err)
	}

	out := make([]*model.UserAddress, 0, len(addrs))
	for _, a := range addrs {
		out = append(out, addressRespToModel(a))
	}
	return out, nil
}

// AddressesByUserID is the resolver for the addressesByUserID field.
func (r *queryResolver) AddressesByUserID(ctx context.Context, userID uuid.UUID) ([]*model.UserAddress, error) {
	// Accessible to the owner or an admin
	callerID := middleware.UserIDFromContext(ctx)
	if callerID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	addrs, err := r.GetAddressUC.Execute(ctx, userID.String())
	if err != nil {
		return nil, mapErr(err)
	}

	out := make([]*model.UserAddress, 0, len(addrs))
	for _, a := range addrs {
		out = append(out, addressRespToModel(a))
	}
	return out, nil
}

// Addresses is the resolver for the addresses field.
func (r *userProfileResolver) Addresses(ctx context.Context, obj *model.UserProfile) ([]*model.UserAddress, error) {
	callerID := middleware.UserIDFromContext(ctx)
	if callerID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}
	if obj.ID != callerID {
		return nil, domainErr.ErrUnauthorized
	}
	addrs, err := r.GetAddressUC.Execute(ctx, obj.ID.String())
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.UserAddress, 0, len(addrs))
	for _, a := range addrs {
		out = append(out, addressRespToModel(a))
	}
	return out, nil
}

// UserProfile returns generated.UserProfileResolver implementation.
func (r *Resolver) UserProfile() generated.UserProfileResolver { return &userProfileResolver{r} }

type userProfileResolver struct{ *Resolver }
