package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"log/slog"

	"github.com/google/uuid"
	"github.com/masterfabric/masterfabric_go_basic/internal/application/usermessage/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// MarkUserMessageRead is the resolver for the markUserMessageRead field.
func (r *mutationResolver) MarkUserMessageRead(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.MarkUserMessageReadUC.Execute(ctx, id.String())
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// AdminCreateUserMessage is the resolver for the adminCreateUserMessage field.
func (r *mutationResolver) AdminCreateUserMessage(ctx context.Context, input model.CreateUserMessageInput) (*model.UserMessagePayload, error) {
	req := &dto.CreateUserMessageRequest{
		UserID:  input.UserID.String(),
		Message: input.Message,
	}
	if input.Type != nil {
		req.Type = *input.Type
	}
	resp, err := r.AdminCreateUserMessageUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	payload := &model.UserMessagePayload{
		ID:        uuid.MustParse(resp.ID),
		UserID:    uuid.MustParse(resp.UserID),
		Message:   resp.Message,
		Type:      resp.Type,
		CreatedAt: resp.CreatedAt,
		ReadAt:    resp.ReadAt,
	}
	// Broadcast for real-time delivery
	r.UserMessageBroadcaster.Broadcast(input.UserID, payload)
	return payload, nil
}

// AdminDeleteUserMessage is the resolver for the adminDeleteUserMessage field.
func (r *mutationResolver) AdminDeleteUserMessage(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.AdminDeleteUserMessageUC.Execute(ctx, id.String())
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

// MyUserMessages is the resolver for the myUserMessages field.
func (r *queryResolver) MyUserMessages(ctx context.Context, limit *int) ([]*model.UserMessagePayload, error) {
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	resp, err := r.ListUserMessagesUC.Execute(ctx, lim)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.UserMessagePayload, 0, len(resp))
	for _, m := range resp {
		out = append(out, &model.UserMessagePayload{
			ID:        uuid.MustParse(m.ID),
			UserID:    uuid.MustParse(m.UserID),
			Message:   m.Message,
			Type:      m.Type,
			CreatedAt: m.CreatedAt,
			ReadAt:    m.ReadAt,
		})
	}
	return out, nil
}

// UserMessageCreated is the resolver for the userMessageCreated field.
func (r *subscriptionResolver) UserMessageCreated(ctx context.Context) (<-chan *model.UserMessagePayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}
	slog.Info("graphql subscription start", slog.String("subscription", "userMessageCreated"), slog.String("user_id", userID.String()))
	ch := r.UserMessageBroadcaster.Subscribe(userID)
	go func() {
		<-ctx.Done()
		slog.Info("graphql subscription end", slog.String("subscription", "userMessageCreated"), slog.String("user_id", userID.String()))
		r.UserMessageBroadcaster.Unsubscribe(userID, ch)
	}()
	return ch, nil
}
