// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AdminAppSetting struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
	IsPublic    bool   `json:"isPublic"`
}

type AdminAppSettingInput struct {
	Key         string  `json:"key"`
	Value       string  `json:"value"`
	Description *string `json:"description,omitempty"`
	IsPublic    *bool   `json:"isPublic,omitempty"`
}

type AdminFeedbackThread struct {
	Thread          *FeedbackThread `json:"thread"`
	UserEmail       string          `json:"userEmail"`
	UserDisplayName string          `json:"userDisplayName"`
}

type AdminMailSMTPSettings struct {
	Enabled            bool      `json:"enabled"`
	Host               string    `json:"host"`
	Port               int       `json:"port"`
	Username           string    `json:"username"`
	PasswordConfigured bool      `json:"passwordConfigured"`
	FromAddress        string    `json:"fromAddress"`
	FromName           string    `json:"fromName"`
	SubjectPrefix      string    `json:"subjectPrefix"`
	ImplicitTLS        bool      `json:"implicitTLS"`
	PlainNoTLS         bool      `json:"plainNoTLS"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

// Admin view of an OTP entry (includes the code itself for admin panel delivery).
type AdminOTPEntry struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"userID"`
	Code       string     `json:"code"`
	Channel    OTPChannel `json:"channel"`
	Purpose    OTPPurpose `json:"purpose"`
	Status     OTPStatus  `json:"status"`
	Attempts   int        `json:"attempts"`
	MaxRetries int        `json:"maxRetries"`
	ExpiresAt  time.Time  `json:"expiresAt"`
	VerifiedAt *time.Time `json:"verifiedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

// Per-organization impact when deleting a user who owns the organization (org row is CASCADE-deleted).
type AdminOwnedOrganizationDeletionImpact struct {
	OrganizationID uuid.UUID `json:"organizationID"`
	Name           string    `json:"name"`
	// Other members in this org (they lose access when the organization is removed).
	OtherMemberCount int `json:"otherMemberCount"`
}

type AdminProductReleaseInput struct {
	Version           string `json:"version"`
	ChangelogMarkdown string `json:"changelogMarkdown"`
}

type AdminReplyToFeedbackInput struct {
	ThreadID uuid.UUID `json:"threadID"`
	Message  string    `json:"message"`
}

type AdminRequestOTPInput struct {
	// Target user to generate an OTP for.
	UserID uuid.UUID `json:"userID"`
	// Purpose of the OTP.
	Purpose OTPPurpose `json:"purpose"`
}

type AdminSendTestMailInput struct {
	ToEmail string `json:"toEmail"`
}

type AdminSendUserEmailInput struct {
	UserID  uuid.UUID `json:"userID"`
	Subject string    `json:"subject"`
	Body    string    `json:"body"`
}

// Session stats for admin dashboard.
type AdminSessionStats struct {
	TotalActiveSessions    int `json:"totalActiveSessions"`
	UniqueActiveUsers      int `json:"uniqueActiveUsers"`
	TotalUsers             int `json:"totalUsers"`
	TotalRegisteredDevices int `json:"totalRegisteredDevices"`
}

type AdminUpdateMailSMTPSettingsInput struct {
	Enabled  bool   `json:"enabled"`
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Username string `json:"username"`
	// Omit or null to keep existing password; empty string clears stored password.
	Password      *string `json:"password,omitempty"`
	FromAddress   string  `json:"fromAddress"`
	FromName      string  `json:"fromName"`
	SubjectPrefix string  `json:"subjectPrefix"`
	ImplicitTLS   bool    `json:"implicitTLS"`
	PlainNoTLS    bool    `json:"plainNoTLS"`
}

type AdminUpdateUserTodoInput struct {
	ID         uuid.UUID  `json:"id"`
	Title      *string    `json:"title,omitempty"`
	Completed  *bool      `json:"completed,omitempty"`
	DueAt      *time.Time `json:"dueAt,omitempty"`
	ClearDueAt *bool      `json:"clearDueAt,omitempty"`
}

// Summary shown to admins before adminDeleteUser.
// Matches database ON DELETE CASCADE / SET NULL behavior in migrations.
type AdminUserDeletionImpact struct {
	UserID      uuid.UUID `json:"userID"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	// Todos where this user is the owner (deleted with the user).
	OwnedTodoCount int `json:"ownedTodoCount"`
	// Todos created by other users that assign this user; assignee is cleared (ON DELETE SET NULL).
	TodoAssigneeClearCount int `json:"todoAssigneeClearCount"`
	// organization_members rows for this user (removed when user is deleted).
	OrganizationMembershipCount int `json:"organizationMembershipCount"`
	// Organizations this user owns; each entire org and its memberships are removed.
	OwnedOrganizations              []*AdminOwnedOrganizationDeletionImpact `json:"ownedOrganizations"`
	AddressCount                    int                                     `json:"addressCount"`
	DeviceCount                     int                                     `json:"deviceCount"`
	HasUserSettings                 bool                                    `json:"hasUserSettings"`
	NotificationReadCount           int                                     `json:"notificationReadCount"`
	SessionCount                    int                                     `json:"sessionCount"`
	UserMessageCount                int                                     `json:"userMessageCount"`
	PendingInvitationAsInviterCount int                                     `json:"pendingInvitationAsInviterCount"`
	// Team chat messages in organizations that you authored (removed when your account is deleted).
	OrganizationMessageAuthoredCount int `json:"organizationMessageAuthoredCount"`
	// Organization news posts you authored (removed when your account is deleted).
	OrganizationNewsAuthoredCount int `json:"organizationNewsAuthoredCount"`
	// OTP audit/history rows for your account (removed when your account is deleted).
	OtpCodeHistoryCount int `json:"otpCodeHistoryCount"`
}

type AdminUserList struct {
	Users      []*AdminUserProfile `json:"users"`
	TotalCount int                 `json:"totalCount"`
	Page       int                 `json:"page"`
	PageSize   int                 `json:"pageSize"`
}

type AdminUserProfile struct {
	ID             uuid.UUID  `json:"id"`
	Email          string     `json:"email"`
	DisplayName    string     `json:"displayName"`
	Nickname       string     `json:"nickname"`
	AvatarURL      string     `json:"avatarURL"`
	Bio            string     `json:"bio"`
	Status         UserStatus `json:"status"`
	Role           UserRole   `json:"role"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	PhoneNumber    string     `json:"phoneNumber"`
	DateOfBirth    *string    `json:"dateOfBirth,omitempty"`
	Gender         Gender     `json:"gender"`
	Location       string     `json:"location"`
	WebsiteURL     string     `json:"websiteURL"`
	SocialTwitter  string     `json:"socialTwitter"`
	SocialGitHub   string     `json:"socialGitHub"`
	SocialLinkedIn string     `json:"socialLinkedIn"`
	Language       string     `json:"language"`
	TelegramChatID string     `json:"telegramChatId"`
}

type AppSetting struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

type AuthPayload struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiresIn    int       `json:"expiresIn"`
	User         *AuthUser `json:"user"`
}

type AuthUser struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	AvatarURL   string    `json:"avatarURL"`
	Role        UserRole  `json:"role"`
}

type CreateNotificationInput struct {
	Title     string  `json:"title"`
	Subtitle  *string `json:"subtitle,omitempty"`
	Message   string  `json:"message"`
	Type      *string `json:"type,omitempty"`
	Category  *string `json:"category,omitempty"`
	Icon      *string `json:"icon,omitempty"`
	Language  *string `json:"language,omitempty"`
	ActionURL *string `json:"actionUrl,omitempty"`
	ImageURL  *string `json:"imageUrl,omitempty"`
	Priority  *string `json:"priority,omitempty"`
	// When true, enqueue a push to all opted-in subscribers via OneSignal (REST on mf-go). Admin-only mutation.
	SendPush *bool `json:"sendPush,omitempty"`
}

type CreateOrganizationInput struct {
	Name string `json:"name"`
}

type CreateOrganizationNewsInput struct {
	OrganizationID uuid.UUID `json:"organizationId"`
	Title          string    `json:"title"`
	Description    *string   `json:"description,omitempty"`
	ImageURL       *string   `json:"imageURL,omitempty"`
	// Optional JSON string for rich metadata.
	RichMetadata *string `json:"richMetadata,omitempty"`
}

type CreateOrganizationProjectInput struct {
	OrganizationID uuid.UUID `json:"organizationId"`
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
}

type CreateOrganizationProjectOrgInviteInput struct {
	ProjectID                 uuid.UUID `json:"projectId"`
	ParticipantOrganizationID uuid.UUID `json:"participantOrganizationId"`
	// JSON object string for capability flags (defaults to {}).
	CapabilitiesJSON *string `json:"capabilitiesJson,omitempty"`
}

type CreateOrganizationProjectPurchaseInput struct {
	ProjectID   uuid.UUID `json:"projectId"`
	ProductName string    `json:"productName"`
	// Tax rate as a non-negative fraction (e.g. 0.2 for 20%). Defaults to 0.
	TaxRate        *float64 `json:"taxRate,omitempty"`
	ProductPurpose *string  `json:"productPurpose,omitempty"`
	Price          float64  `json:"price"`
	// Must be positive. Defaults to 1.
	Quantity    *float64 `json:"quantity,omitempty"`
	ProductLink *string  `json:"productLink,omitempty"`
	// ISO-style code (e.g. TRY, USD). Defaults to TRY.
	Currency *string `json:"currency,omitempty"`
	// Defaults to REQUESTED when omitted.
	Status     *OrganizationProjectPurchaseStatus `json:"status,omitempty"`
	StatusNote *string                            `json:"statusNote,omitempty"`
}

type CreateOrganizationProjectTodoInput struct {
	ProjectID uuid.UUID `json:"projectId"`
	Title     string    `json:"title"`
	// When set, only org admin/owner may assign; user must be on the project roster.
	AssignedToUserID *uuid.UUID `json:"assignedToUserId,omitempty"`
	// Optional due instant (RFC3339).
	DueAt *time.Time `json:"dueAt,omitempty"`
}

type CreateOrganizationProjectTodoSubtaskInput struct {
	ProjectTodoID uuid.UUID `json:"projectTodoId"`
	Title         string    `json:"title"`
	Completed     *bool     `json:"completed,omitempty"`
}

type CreateTodoInput struct {
	Title            string     `json:"title"`
	Completed        *bool      `json:"completed,omitempty"`
	OrganizationID   *uuid.UUID `json:"organizationID,omitempty"`
	AssignedToUserID *uuid.UUID `json:"assignedToUserID,omitempty"`
	// When set, todo is due at this instant (RFC3339). Omit for no due time.
	DueAt *time.Time `json:"dueAt,omitempty"`
}

type CreateUserMessageInput struct {
	UserID  uuid.UUID `json:"userID"`
	Message string    `json:"message"`
	Type    *string   `json:"type,omitempty"`
}

type CreateUserTodoSubtaskInput struct {
	UserTodoID uuid.UUID `json:"userTodoId"`
	Title      string    `json:"title"`
	Completed  *bool     `json:"completed,omitempty"`
}

type FeedbackMessage struct {
	ID         uuid.UUID          `json:"id"`
	ThreadID   uuid.UUID          `json:"threadID"`
	AuthorRole FeedbackAuthorRole `json:"authorRole"`
	Body       string             `json:"body"`
	CreatedAt  time.Time          `json:"createdAt"`
}

type FeedbackThread struct {
	ID uuid.UUID `json:"id"`
	// Set when the submitter was signed in; null for guest-only threads.
	UserID *uuid.UUID `json:"userID,omitempty"`
	// Guest email from submission, if any; empty for account-only threads.
	ContactEmail string             `json:"contactEmail"`
	Subject      string             `json:"subject"`
	Status       string             `json:"status"`
	CreatedAt    time.Time          `json:"createdAt"`
	UpdatedAt    time.Time          `json:"updatedAt"`
	Messages     []*FeedbackMessage `json:"messages"`
}

type InviteToOrganizationInput struct {
	OrganizationID uuid.UUID `json:"organizationId"`
	InviteeEmail   string    `json:"inviteeEmail"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Returned by login. When otpRequired=false, auth fields are populated.
// When otpRequired=true, only loginToken + user are set — use loginVerifyOTP to complete.
type LoginPayload struct {
	OtpRequired bool `json:"otpRequired"`
	// Temporary token for OTP verification (only set when otpRequired=true).
	LoginToken *string `json:"loginToken,omitempty"`
	// Full auth tokens (only set when otpRequired=false).
	AccessToken  *string   `json:"accessToken,omitempty"`
	RefreshToken *string   `json:"refreshToken,omitempty"`
	ExpiresIn    *int      `json:"expiresIn,omitempty"`
	User         *AuthUser `json:"user"`
}

type LoginVerifyOTPInput struct {
	// The temporary login token returned by login when otpRequired=true.
	LoginToken string `json:"loginToken"`
	// The 6-digit OTP code.
	Code string `json:"code"`
}

type LogoutInput struct {
	UserID       uuid.UUID `json:"userID"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
}

type Mutation struct {
}

// Summary of what will be deleted or updated when the authenticated user calls deleteAccount.
type MyAccountDeletionImpact struct {
	// Todos you created (personal and org-linked rows where you are owner user_id).
	OwnedTodoCount int `json:"ownedTodoCount"`
	// Todos created by other people that assigned you; your assignee field is cleared (todo rows stay).
	TodoAssigneeClearCount int `json:"todoAssigneeClearCount"`
	// Organizations you are a member of; you are removed from each (orgs you do not own stay).
	OrganizationMembershipCount int                                  `json:"organizationMembershipCount"`
	OwnedOrganizations          []*MyOwnedOrganizationDeletionImpact `json:"ownedOrganizations"`
	AddressCount                int                                  `json:"addressCount"`
	DeviceCount                 int                                  `json:"deviceCount"`
	HasUserSettings             bool                                 `json:"hasUserSettings"`
	NotificationReadCount       int                                  `json:"notificationReadCount"`
	SessionCount                int                                  `json:"sessionCount"`
	// In-app admin/user messages delivered to you.
	UserMessageCount                int `json:"userMessageCount"`
	PendingInvitationAsInviterCount int `json:"pendingInvitationAsInviterCount"`
	// Team chat messages you posted in organizations.
	OrganizationMessageAuthoredCount int `json:"organizationMessageAuthoredCount"`
	// Organization news posts you authored.
	OrganizationNewsAuthoredCount int `json:"organizationNewsAuthoredCount"`
	// OTP request history rows for your account.
	OtpCodeHistoryCount int `json:"otpCodeHistoryCount"`
}

// Organizations you own; deleting your account removes each entire org and its data (members, chat, news, etc.).
type MyOwnedOrganizationDeletionImpact struct {
	OrganizationID uuid.UUID `json:"organizationID"`
	Name           string    `json:"name"`
	// Other members in this org (they lose access when the organization is removed).
	OtherMemberCount int `json:"otherMemberCount"`
}

type NotificationPayload struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Subtitle  *string   `json:"subtitle,omitempty"`
	Message   string    `json:"message"`
	Type      string    `json:"type"`
	Category  string    `json:"category"`
	Icon      *string   `json:"icon,omitempty"`
	Language  *string   `json:"language,omitempty"`
	ActionURL *string   `json:"actionUrl,omitempty"`
	ImageURL  *string   `json:"imageUrl,omitempty"`
	Priority  *string   `json:"priority,omitempty"`
	IsRead    bool      `json:"isRead"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type OTPRequestPayload struct {
	// ID of the generated OTP record.
	OtpID uuid.UUID `json:"otpID"`
	// Channel used for delivery.
	Channel OTPChannel `json:"channel"`
	// When the code expires.
	ExpiresAt time.Time `json:"expiresAt"`
}

type OTPVerifyPayload struct {
	// True if the code was correct.
	Verified bool `json:"verified"`
	// ID of the verified OTP record.
	OtpID uuid.UUID `json:"otpID"`
}

type Organization struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	LogoURL      string    `json:"logoURL"`
	WebsiteURL   string    `json:"websiteURL"`
	ContactEmail string    `json:"contactEmail"`
	OwnerUserID  uuid.UUID `json:"ownerUserID"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type OrganizationInvitation struct {
	ID             uuid.UUID                    `json:"id"`
	OrganizationID uuid.UUID                    `json:"organizationID"`
	InviterID      uuid.UUID                    `json:"inviterID"`
	InviteeEmail   string                       `json:"inviteeEmail"`
	Status         OrganizationInvitationStatus `json:"status"`
	CreatedAt      time.Time                    `json:"createdAt"`
	// Set when listing the invitee's pending invitations (organization name for display).
	OrganizationName *string `json:"organizationName,omitempty"`
	// Inviter display name when listing the invitee's pending invitations (nickname or display name).
	InviterNickname *string `json:"inviterNickname,omitempty"`
}

type OrganizationMember struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organizationID"`
	UserID         uuid.UUID `json:"userID"`
	// Display nickname of the user (from their profile).
	UserNickname     string                       `json:"userNickname"`
	Role             OrganizationMemberRole       `json:"role"`
	MembershipStatus OrganizationMembershipStatus `json:"membershipStatus"`
	JoinedAt         time.Time                    `json:"joinedAt"`
}

type OrganizationMessage struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organizationID"`
	AuthorUserID   uuid.UUID `json:"authorUserID"`
	AuthorNickname string    `json:"authorNickname"`
	Body           string    `json:"body"`
	CreatedAt      time.Time `json:"createdAt"`
}

type OrganizationNews struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organizationID"`
	AuthorUserID   uuid.UUID `json:"authorUserID"`
	AuthorNickname string    `json:"authorNickname"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	ImageURL       string    `json:"imageURL"`
	RichMetadata   *string   `json:"richMetadata,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type OrganizationOwnerAssigneeSlice struct {
	UserID    *uuid.UUID `json:"userId,omitempty"`
	Nickname  *string    `json:"nickname,omitempty"`
	OpenCount int        `json:"openCount"`
}

type OrganizationOwnerDashboardDayBucket struct {
	// Start of day UTC (00:00) for the bucket.
	Day            time.Time `json:"day"`
	CompletedCount int       `json:"completedCount"`
}

type OrganizationOwnerProjectDoneInPeriod struct {
	// Null when isGeneral: org-scoped user todos (not tied to a project).
	ProjectID   *uuid.UUID `json:"projectId,omitempty"`
	ProjectName *string    `json:"projectName,omitempty"`
	IsGeneral   bool       `json:"isGeneral"`
	Count       int        `json:"count"`
}

type OrganizationOwnerTodoDashboard struct {
	OrganizationID      uuid.UUID                        `json:"organizationId"`
	Period              OrganizationOwnerDashboardPeriod `json:"period"`
	IncludeSubtasks     bool                             `json:"includeSubtasks"`
	PeriodStart         time.Time                        `json:"periodStart"`
	PeriodEnd           time.Time                        `json:"periodEnd"`
	PreviousPeriodStart time.Time                        `json:"previousPeriodStart"`
	PreviousPeriodEnd   time.Time                        `json:"previousPeriodEnd"`
	// All countable units in scope, not in done state (mode A: roots; mode B: roots + subtask lines).
	OpenCount int `json:"openCount"`
	// All countable units in scope, done.
	DoneCount int `json:"doneCount"`
	// Units completed in the selected period (completion proxy: completed status + updated_at in window).
	CompletedInSelectedPeriod int `json:"completedInSelectedPeriod"`
	// Same count rule, previous period window (for client PoP % with ±12% thresholds).
	CompletedInPreviousPeriod int                                    `json:"completedInPreviousPeriod"`
	DailySeries               []*OrganizationOwnerDashboardDayBucket `json:"dailySeries"`
	// For donut 1: same as openCount / doneCount (explicit for chart).
	DonutOpenCount        int                                     `json:"donutOpenCount"`
	DonutDoneCount        int                                     `json:"donutDoneCount"`
	DoneInPeriodByProject []*OrganizationOwnerProjectDoneInPeriod `json:"doneInPeriodByProject"`
	// Open (not done) units by assignee; null userId = Unassigned.
	OpenByAssignee []*OrganizationOwnerAssigneeSlice `json:"openByAssignee"`
}

type OrganizationOwnerTodoDashboardInput struct {
	OrganizationID uuid.UUID                        `json:"organizationId"`
	Period         OrganizationOwnerDashboardPeriod `json:"period"`
	// 0 = current week or month, 1 = one period earlier, etc.
	PeriodOffset int `json:"periodOffset"`
	// Mode B: include each subtask as its own unit; false = mode A (roots only).
	IncludeSubtasks bool `json:"includeSubtasks"`
	// When null or empty, all projects in the organization are included in project-todo parts.
	// General (org user todos without a project) are always included in scope.
	ProjectIds []uuid.UUID `json:"projectIds,omitempty"`
}

type OrganizationProject struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organizationId"`
	Name            string    `json:"name"`
	Description     string    `json:"description"`
	CreatedByUserID uuid.UUID `json:"createdByUserId"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type OrganizationProjectMember struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"projectId"`
	UserID       uuid.UUID `json:"userId"`
	UserNickname string    `json:"userNickname"`
	AddedAt      time.Time `json:"addedAt"`
}

type OrganizationProjectMyCapabilities struct {
	CanEditTodos     bool `json:"canEditTodos"`
	CanEditPurchases bool `json:"canEditPurchases"`
}

type OrganizationProjectOrgInvitePendingRow struct {
	ProjectID            uuid.UUID `json:"projectId"`
	ProjectName          string    `json:"projectName"`
	HostOrganizationID   uuid.UUID `json:"hostOrganizationId"`
	HostOrganizationName string    `json:"hostOrganizationName"`
	InvitedAt            time.Time `json:"invitedAt"`
	CapabilitiesJSON     string    `json:"capabilitiesJson"`
}

type OrganizationProjectOrgParticipation struct {
	ID                        uuid.UUID                                 `json:"id"`
	ProjectID                 uuid.UUID                                 `json:"projectId"`
	ParticipantOrganizationID uuid.UUID                                 `json:"participantOrganizationId"`
	Status                    OrganizationProjectOrgParticipationStatus `json:"status"`
	// JSON object string (capability flags).
	CapabilitiesJSON string     `json:"capabilitiesJson"`
	InvitedByUserID  *uuid.UUID `json:"invitedByUserId,omitempty"`
	InvitedAt        time.Time  `json:"invitedAt"`
	RespondedAt      *time.Time `json:"respondedAt,omitempty"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdatedAt        time.Time  `json:"updatedAt"`
}

type OrganizationProjectOrgParticipationRow struct {
	ParticipationID             uuid.UUID                                 `json:"participationId"`
	ProjectID                   uuid.UUID                                 `json:"projectId"`
	ParticipantOrganizationID   uuid.UUID                                 `json:"participantOrganizationId"`
	ParticipantOrganizationName string                                    `json:"participantOrganizationName"`
	Status                      OrganizationProjectOrgParticipationStatus `json:"status"`
	CapabilitiesJSON            string                                    `json:"capabilitiesJson"`
	InvitedByUserID             *uuid.UUID                                `json:"invitedByUserId,omitempty"`
	InvitedAt                   time.Time                                 `json:"invitedAt"`
	RespondedAt                 *time.Time                                `json:"respondedAt,omitempty"`
	CreatedAt                   time.Time                                 `json:"createdAt"`
	UpdatedAt                   time.Time                                 `json:"updatedAt"`
}

type OrganizationProjectPurchase struct {
	ID              uuid.UUID                         `json:"id"`
	ProjectID       uuid.UUID                         `json:"projectId"`
	ProductName     string                            `json:"productName"`
	TaxRate         float64                           `json:"taxRate"`
	ProductPurpose  string                            `json:"productPurpose"`
	Price           float64                           `json:"price"`
	Quantity        float64                           `json:"quantity"`
	ProductLink     *string                           `json:"productLink,omitempty"`
	Status          OrganizationProjectPurchaseStatus `json:"status"`
	StatusNote      string                            `json:"statusNote"`
	Currency        string                            `json:"currency"`
	CreatedByUserID uuid.UUID                         `json:"createdByUserId"`
	CreatedAt       time.Time                         `json:"createdAt"`
	UpdatedAt       time.Time                         `json:"updatedAt"`
}

type OrganizationProjectTodo struct {
	ID               uuid.UUID                     `json:"id"`
	ProjectID        uuid.UUID                     `json:"projectId"`
	Title            string                        `json:"title"`
	Status           OrganizationProjectTodoStatus `json:"status"`
	CreatedByUserID  uuid.UUID                     `json:"createdByUserId"`
	AssignedToUserID *uuid.UUID                    `json:"assignedToUserId,omitempty"`
	DueAt            *time.Time                    `json:"dueAt,omitempty"`
	CreatedAt        time.Time                     `json:"createdAt"`
	UpdatedAt        time.Time                     `json:"updatedAt"`
	// Single-level checklist items under this task.
	Subtasks []*OrganizationProjectTodoSubtask `json:"subtasks"`
}

type OrganizationProjectTodoSubtask struct {
	ID            uuid.UUID `json:"id"`
	ProjectTodoID uuid.UUID `json:"projectTodoId"`
	Title         string    `json:"title"`
	Completed     bool      `json:"completed"`
	SortOrder     int       `json:"sortOrder"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type PasswordResetRequestedPayload struct {
	Ok bool `json:"ok"`
}

type ProductRelease struct {
	Version string `json:"version"`
	// Markdown body (e.g. sections per release: version, date, author, changes).
	ChangelogMarkdown string    `json:"changelogMarkdown"`
	UpdatedAt         time.Time `json:"updatedAt"`
	// Display name of the admin who last published this release info.
	UpdatedByDisplayName *string `json:"updatedByDisplayName,omitempty"`
}

type Query struct {
}

type RefreshInput struct {
	UserID       uuid.UUID `json:"userID"`
	RefreshToken string    `json:"refreshToken"`
	// Optional: device ID for session tracking (admin can see active sessions).
	DeviceID *string `json:"deviceID,omitempty"`
	// Optional: platform (ios, android, web) for session display.
	Platform *string `json:"platform,omitempty"`
	// Optional: device name for admin session list.
	DeviceName *string `json:"deviceName,omitempty"`
}

type RegisterDeviceInput struct {
	DeviceID   string  `json:"deviceId"`
	Platform   string  `json:"platform"`
	DeviceName *string `json:"deviceName,omitempty"`
	Model      *string `json:"model,omitempty"`
	Brand      *string `json:"brand,omitempty"`
	OsName     *string `json:"osName,omitempty"`
	OsVersion  *string `json:"osVersion,omitempty"`
	AppName    *string `json:"appName,omitempty"`
	AppVersion *string `json:"appVersion,omitempty"`
	AppBuild   *string `json:"appBuild,omitempty"`
}

type RegisterInput struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

type RequestOTPInput struct {
	// Purpose of the OTP: LOGIN, VERIFY_IDENTITY, PASSWORD_RESET, ACCOUNT_ACTIVATE, EMAIL_CHANGE.
	Purpose OTPPurpose `json:"purpose"`
}

type RequestPasswordResetInput struct {
	Email string `json:"email"`
}

type ResetPasswordWithOtpInput struct {
	Email       string `json:"email"`
	Code        string `json:"code"`
	NewPassword string `json:"newPassword"`
}

type SubmitFeedbackInput struct {
	// Optional short title; defaults to \"Feedback\" when omitted or blank.
	Subject *string `json:"subject,omitempty"`
	Message string  `json:"message"`
	// Required when the request is not authenticated: an email the team can reply to.
	// Ignored when a valid access token is present.
	ContactEmail *string `json:"contactEmail,omitempty"`
}

type Subscription struct {
}

type UpdateNotificationInput struct {
	Title     *string `json:"title,omitempty"`
	Subtitle  *string `json:"subtitle,omitempty"`
	Message   *string `json:"message,omitempty"`
	Type      *string `json:"type,omitempty"`
	Category  *string `json:"category,omitempty"`
	Icon      *string `json:"icon,omitempty"`
	Language  *string `json:"language,omitempty"`
	ActionURL *string `json:"actionUrl,omitempty"`
	ImageURL  *string `json:"imageUrl,omitempty"`
	Priority  *string `json:"priority,omitempty"`
}

type UpdateOrganizationInput struct {
	OrganizationID uuid.UUID `json:"organizationId"`
	Name           *string   `json:"name,omitempty"`
	Description    *string   `json:"description,omitempty"`
	LogoURL        *string   `json:"logoURL,omitempty"`
	WebsiteURL     *string   `json:"websiteURL,omitempty"`
	ContactEmail   *string   `json:"contactEmail,omitempty"`
}

type UpdateOrganizationNewsInput struct {
	NewsID       uuid.UUID `json:"newsId"`
	Title        *string   `json:"title,omitempty"`
	Description  *string   `json:"description,omitempty"`
	ImageURL     *string   `json:"imageURL,omitempty"`
	RichMetadata *string   `json:"richMetadata,omitempty"`
}

type UpdateOrganizationProjectInput struct {
	ProjectID   uuid.UUID `json:"projectId"`
	Name        *string   `json:"name,omitempty"`
	Description *string   `json:"description,omitempty"`
}

type UpdateOrganizationProjectPurchaseInput struct {
	PurchaseID     uuid.UUID `json:"purchaseId"`
	ProductName    *string   `json:"productName,omitempty"`
	TaxRate        *float64  `json:"taxRate,omitempty"`
	ProductPurpose *string   `json:"productPurpose,omitempty"`
	Price          *float64  `json:"price,omitempty"`
	Quantity       *float64  `json:"quantity,omitempty"`
	ProductLink    *string   `json:"productLink,omitempty"`
	// When true, clears productLink regardless of productLink.
	ClearProductLink *bool                              `json:"clearProductLink,omitempty"`
	Status           *OrganizationProjectPurchaseStatus `json:"status,omitempty"`
	StatusNote       *string                            `json:"statusNote,omitempty"`
	Currency         *string                            `json:"currency,omitempty"`
}

type UpdateOrganizationProjectTodoInput struct {
	TodoID     uuid.UUID                      `json:"todoId"`
	Title      *string                        `json:"title,omitempty"`
	Status     *OrganizationProjectTodoStatus `json:"status,omitempty"`
	DueAt      *time.Time                     `json:"dueAt,omitempty"`
	ClearDueAt *bool                          `json:"clearDueAt,omitempty"`
}

type UpdateOrganizationProjectTodoSubtaskInput struct {
	ID        uuid.UUID `json:"id"`
	Title     *string   `json:"title,omitempty"`
	Completed *bool     `json:"completed,omitempty"`
}

type UpdateProfileInput struct {
	// New sign-in email (normalized to lowercase). Must be unique; omit to leave unchanged.
	Email *string `json:"email,omitempty"`
	// Required when changing email: the otpID returned from verifyOTP after verifying an EMAIL_CHANGE code
	// sent to your current address. Must be verified within the last few minutes.
	EmailChangeOtpID *uuid.UUID `json:"emailChangeOtpId,omitempty"`
	DisplayName      *string    `json:"displayName,omitempty"`
	Nickname         *string    `json:"nickname,omitempty"`
	AvatarURL        *string    `json:"avatarURL,omitempty"`
	Bio              *string    `json:"bio,omitempty"`
	PhoneNumber      *string    `json:"phoneNumber,omitempty"`
	// Numeric Telegram chat id from @userinfobot or your bot's /start webhook (for Telegram OTP).
	TelegramChatID *string `json:"telegramChatId,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	Gender         *Gender `json:"gender,omitempty"`
	Location       *string `json:"location,omitempty"`
	WebsiteURL     *string `json:"websiteURL,omitempty"`
	SocialTwitter  *string `json:"socialTwitter,omitempty"`
	SocialGitHub   *string `json:"socialGitHub,omitempty"`
	SocialLinkedIn *string `json:"socialLinkedIn,omitempty"`
	Language       *string `json:"language,omitempty"`
}

type UpdateTodoInput struct {
	ID                uuid.UUID  `json:"id"`
	Title             *string    `json:"title,omitempty"`
	Completed         *bool      `json:"completed,omitempty"`
	OrganizationID    *uuid.UUID `json:"organizationID,omitempty"`
	ClearOrganization *bool      `json:"clearOrganization,omitempty"`
	AssignedToUserID  *uuid.UUID `json:"assignedToUserID,omitempty"`
	// Set or replace due time (RFC3339). Omit to leave unchanged unless clearDueAt is set.
	DueAt *time.Time `json:"dueAt,omitempty"`
	// When true, clears due time.
	ClearDueAt *bool `json:"clearDueAt,omitempty"`
}

type UpdateUserTodoSubtaskInput struct {
	ID        uuid.UUID `json:"id"`
	Title     *string   `json:"title,omitempty"`
	Completed *bool     `json:"completed,omitempty"`
}

type UpsertAddressInput struct {
	AddressID    *uuid.UUID `json:"addressID,omitempty"`
	Title        *string    `json:"title,omitempty"`
	AddressLine1 *string    `json:"addressLine1,omitempty"`
	AddressLine2 *string    `json:"addressLine2,omitempty"`
	City         *string    `json:"city,omitempty"`
	State        *string    `json:"state,omitempty"`
	PostalCode   *string    `json:"postalCode,omitempty"`
	Country      *string    `json:"country,omitempty"`
	IsDefault    *bool      `json:"isDefault,omitempty"`
}

type UserAddress struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"userID"`
	Title        string    `json:"title"`
	AddressLine1 string    `json:"addressLine1"`
	AddressLine2 string    `json:"addressLine2"`
	City         string    `json:"city"`
	State        string    `json:"state"`
	PostalCode   string    `json:"postalCode"`
	Country      string    `json:"country"`
	IsDefault    bool      `json:"isDefault"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type UserDevice struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"userID"`
	DeviceID   string    `json:"deviceId"`
	Platform   string    `json:"platform"`
	DeviceName string    `json:"deviceName"`
	Model      string    `json:"model"`
	Brand      string    `json:"brand"`
	OsName     string    `json:"osName"`
	OsVersion  string    `json:"osVersion"`
	AppName    string    `json:"appName"`
	AppVersion string    `json:"appVersion"`
	AppBuild   string    `json:"appBuild"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type UserMessagePayload struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"userID"`
	Message   string     `json:"message"`
	Type      string     `json:"type"`
	CreatedAt time.Time  `json:"createdAt"`
	ReadAt    *time.Time `json:"readAt,omitempty"`
}

type UserProfile struct {
	ID             uuid.UUID  `json:"id"`
	Email          string     `json:"email"`
	DisplayName    string     `json:"displayName"`
	Nickname       string     `json:"nickname"`
	AvatarURL      string     `json:"avatarURL"`
	Bio            string     `json:"bio"`
	Status         UserStatus `json:"status"`
	Role           UserRole   `json:"role"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	PhoneNumber    string     `json:"phoneNumber"`
	DateOfBirth    *string    `json:"dateOfBirth,omitempty"`
	Gender         Gender     `json:"gender"`
	Location       string     `json:"location"`
	WebsiteURL     string     `json:"websiteURL"`
	SocialTwitter  string     `json:"socialTwitter"`
	SocialGitHub   string     `json:"socialGitHub"`
	SocialLinkedIn string     `json:"socialLinkedIn"`
	Language       string     `json:"language"`
	// Linked Telegram chat id for OTP delivery when OTP_DELIVERY=telegram.
	TelegramChatID string `json:"telegramChatId"`
	// The user's default address, if one has been set.
	Address *UserAddress `json:"address,omitempty"`
	// All saved addresses for this user (same data as myAddresses for the profile owner).
	Addresses []*UserAddress `json:"addresses"`
}

// Active user session — device, platform, last refresh time, user and org info.
type UserSession struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"userID"`
	UserEmail         string    `json:"userEmail"`
	UserDisplayName   string    `json:"userDisplayName"`
	OrganizationNames []string  `json:"organizationNames"`
	DeviceID          string    `json:"deviceID"`
	Platform          string    `json:"platform"`
	DeviceName        string    `json:"deviceName"`
	CreatedAt         time.Time `json:"createdAt"`
	LastRefreshedAt   time.Time `json:"lastRefreshedAt"`
}

type UserSettingsInput struct {
	NotificationsOn *bool   `json:"notificationsOn,omitempty"`
	Theme           *Theme  `json:"theme,omitempty"`
	Language        *string `json:"language,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
	// Enable or disable OTP two-factor authentication for login.
	OtpEnabled *bool `json:"otpEnabled,omitempty"`
}

type UserSettingsPayload struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"userID"`
	NotificationsOn bool      `json:"notificationsOn"`
	Theme           Theme     `json:"theme"`
	Language        string    `json:"language"`
	Timezone        string    `json:"timezone"`
	// Whether OTP two-factor authentication is enabled for this user.
	OtpEnabled bool      `json:"otpEnabled"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type UserTodo struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"userID"`
	Title            string     `json:"title"`
	Completed        bool       `json:"completed"`
	OrganizationID   *uuid.UUID `json:"organizationID,omitempty"`
	AssignedToUserID *uuid.UUID `json:"assignedToUserID,omitempty"`
	// When set, scheduled due moment (UTC).
	DueAt     *time.Time `json:"dueAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	// Single-level checklist items under this task.
	Subtasks []*UserTodoSubtask `json:"subtasks"`
}

type UserTodoSubtask struct {
	ID         uuid.UUID `json:"id"`
	UserTodoID uuid.UUID `json:"userTodoId"`
	Title      string    `json:"title"`
	Completed  bool      `json:"completed"`
	SortOrder  int       `json:"sortOrder"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type VerifyOTPInput struct {
	// The 6-digit code the user received.
	Code string `json:"code"`
	// Purpose must match the original request.
	Purpose OTPPurpose `json:"purpose"`
}

type FeedbackAuthorRole string

const (
	FeedbackAuthorRoleUser  FeedbackAuthorRole = "USER"
	FeedbackAuthorRoleAdmin FeedbackAuthorRole = "ADMIN"
)

var AllFeedbackAuthorRole = []FeedbackAuthorRole{
	FeedbackAuthorRoleUser,
	FeedbackAuthorRoleAdmin,
}

func (e FeedbackAuthorRole) IsValid() bool {
	switch e {
	case FeedbackAuthorRoleUser, FeedbackAuthorRoleAdmin:
		return true
	}
	return false
}

func (e FeedbackAuthorRole) String() string {
	return string(e)
}

func (e *FeedbackAuthorRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FeedbackAuthorRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FeedbackAuthorRole", str)
	}
	return nil
}

func (e FeedbackAuthorRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Gender string

const (
	GenderMale           Gender = "MALE"
	GenderFemale         Gender = "FEMALE"
	GenderOther          Gender = "OTHER"
	GenderPreferNotToSay Gender = "PREFER_NOT_TO_SAY"
	GenderUnspecified    Gender = "UNSPECIFIED"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
	GenderOther,
	GenderPreferNotToSay,
	GenderUnspecified,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale, GenderOther, GenderPreferNotToSay, GenderUnspecified:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OTPChannel string

const (
	OTPChannelAdminPanel OTPChannel = "ADMIN_PANEL"
	OTPChannelEmail      OTPChannel = "EMAIL"
	OTPChannelSms        OTPChannel = "SMS"
	OTPChannelWhatsapp   OTPChannel = "WHATSAPP"
	OTPChannelTelegram   OTPChannel = "TELEGRAM"
)

var AllOTPChannel = []OTPChannel{
	OTPChannelAdminPanel,
	OTPChannelEmail,
	OTPChannelSms,
	OTPChannelWhatsapp,
	OTPChannelTelegram,
}

func (e OTPChannel) IsValid() bool {
	switch e {
	case OTPChannelAdminPanel, OTPChannelEmail, OTPChannelSms, OTPChannelWhatsapp, OTPChannelTelegram:
		return true
	}
	return false
}

func (e OTPChannel) String() string {
	return string(e)
}

func (e *OTPChannel) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OTPChannel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OTPChannel", str)
	}
	return nil
}

func (e OTPChannel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OTPPurpose string

const (
	OTPPurposeLogin           OTPPurpose = "LOGIN"
	OTPPurposeVerifyIDEntity  OTPPurpose = "VERIFY_IDENTITY"
	OTPPurposePasswordReset   OTPPurpose = "PASSWORD_RESET"
	OTPPurposeAccountActivate OTPPurpose = "ACCOUNT_ACTIVATE"
	// Code sent to your current sign-in email before changing it (see updateProfile.email + emailChangeOtpId).
	OTPPurposeEmailChange OTPPurpose = "EMAIL_CHANGE"
)

var AllOTPPurpose = []OTPPurpose{
	OTPPurposeLogin,
	OTPPurposeVerifyIDEntity,
	OTPPurposePasswordReset,
	OTPPurposeAccountActivate,
	OTPPurposeEmailChange,
}

func (e OTPPurpose) IsValid() bool {
	switch e {
	case OTPPurposeLogin, OTPPurposeVerifyIDEntity, OTPPurposePasswordReset, OTPPurposeAccountActivate, OTPPurposeEmailChange:
		return true
	}
	return false
}

func (e OTPPurpose) String() string {
	return string(e)
}

func (e *OTPPurpose) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OTPPurpose(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OTPPurpose", str)
	}
	return nil
}

func (e OTPPurpose) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OTPStatus string

const (
	OTPStatusPending  OTPStatus = "PENDING"
	OTPStatusVerified OTPStatus = "VERIFIED"
	OTPStatusExpired  OTPStatus = "EXPIRED"
)

var AllOTPStatus = []OTPStatus{
	OTPStatusPending,
	OTPStatusVerified,
	OTPStatusExpired,
}

func (e OTPStatus) IsValid() bool {
	switch e {
	case OTPStatusPending, OTPStatusVerified, OTPStatusExpired:
		return true
	}
	return false
}

func (e OTPStatus) String() string {
	return string(e)
}

func (e *OTPStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OTPStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OTPStatus", str)
	}
	return nil
}

func (e OTPStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationInvitationStatus string

const (
	OrganizationInvitationStatusPending  OrganizationInvitationStatus = "PENDING"
	OrganizationInvitationStatusAccepted OrganizationInvitationStatus = "ACCEPTED"
	OrganizationInvitationStatusDeclined OrganizationInvitationStatus = "DECLINED"
	OrganizationInvitationStatusRevoked  OrganizationInvitationStatus = "REVOKED"
)

var AllOrganizationInvitationStatus = []OrganizationInvitationStatus{
	OrganizationInvitationStatusPending,
	OrganizationInvitationStatusAccepted,
	OrganizationInvitationStatusDeclined,
	OrganizationInvitationStatusRevoked,
}

func (e OrganizationInvitationStatus) IsValid() bool {
	switch e {
	case OrganizationInvitationStatusPending, OrganizationInvitationStatusAccepted, OrganizationInvitationStatusDeclined, OrganizationInvitationStatusRevoked:
		return true
	}
	return false
}

func (e OrganizationInvitationStatus) String() string {
	return string(e)
}

func (e *OrganizationInvitationStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationInvitationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationInvitationStatus", str)
	}
	return nil
}

func (e OrganizationInvitationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationMemberRole string

const (
	OrganizationMemberRoleOwner  OrganizationMemberRole = "OWNER"
	OrganizationMemberRoleAdmin  OrganizationMemberRole = "ADMIN"
	OrganizationMemberRoleMember OrganizationMemberRole = "MEMBER"
)

var AllOrganizationMemberRole = []OrganizationMemberRole{
	OrganizationMemberRoleOwner,
	OrganizationMemberRoleAdmin,
	OrganizationMemberRoleMember,
}

func (e OrganizationMemberRole) IsValid() bool {
	switch e {
	case OrganizationMemberRoleOwner, OrganizationMemberRoleAdmin, OrganizationMemberRoleMember:
		return true
	}
	return false
}

func (e OrganizationMemberRole) String() string {
	return string(e)
}

func (e *OrganizationMemberRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationMemberRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationMemberRole", str)
	}
	return nil
}

func (e OrganizationMemberRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationMembershipStatus string

const (
	OrganizationMembershipStatusActive    OrganizationMembershipStatus = "ACTIVE"
	OrganizationMembershipStatusSuspended OrganizationMembershipStatus = "SUSPENDED"
)

var AllOrganizationMembershipStatus = []OrganizationMembershipStatus{
	OrganizationMembershipStatusActive,
	OrganizationMembershipStatusSuspended,
}

func (e OrganizationMembershipStatus) IsValid() bool {
	switch e {
	case OrganizationMembershipStatusActive, OrganizationMembershipStatusSuspended:
		return true
	}
	return false
}

func (e OrganizationMembershipStatus) String() string {
	return string(e)
}

func (e *OrganizationMembershipStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationMembershipStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationMembershipStatus", str)
	}
	return nil
}

func (e OrganizationMembershipStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationOwnerDashboardPeriod string

const (
	OrganizationOwnerDashboardPeriodWeek  OrganizationOwnerDashboardPeriod = "WEEK"
	OrganizationOwnerDashboardPeriodMonth OrganizationOwnerDashboardPeriod = "MONTH"
)

var AllOrganizationOwnerDashboardPeriod = []OrganizationOwnerDashboardPeriod{
	OrganizationOwnerDashboardPeriodWeek,
	OrganizationOwnerDashboardPeriodMonth,
}

func (e OrganizationOwnerDashboardPeriod) IsValid() bool {
	switch e {
	case OrganizationOwnerDashboardPeriodWeek, OrganizationOwnerDashboardPeriodMonth:
		return true
	}
	return false
}

func (e OrganizationOwnerDashboardPeriod) String() string {
	return string(e)
}

func (e *OrganizationOwnerDashboardPeriod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationOwnerDashboardPeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationOwnerDashboardPeriod", str)
	}
	return nil
}

func (e OrganizationOwnerDashboardPeriod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationProjectOrgParticipationStatus string

const (
	OrganizationProjectOrgParticipationStatusPending  OrganizationProjectOrgParticipationStatus = "PENDING"
	OrganizationProjectOrgParticipationStatusAccepted OrganizationProjectOrgParticipationStatus = "ACCEPTED"
	OrganizationProjectOrgParticipationStatusDeclined OrganizationProjectOrgParticipationStatus = "DECLINED"
	OrganizationProjectOrgParticipationStatusRevoked  OrganizationProjectOrgParticipationStatus = "REVOKED"
)

var AllOrganizationProjectOrgParticipationStatus = []OrganizationProjectOrgParticipationStatus{
	OrganizationProjectOrgParticipationStatusPending,
	OrganizationProjectOrgParticipationStatusAccepted,
	OrganizationProjectOrgParticipationStatusDeclined,
	OrganizationProjectOrgParticipationStatusRevoked,
}

func (e OrganizationProjectOrgParticipationStatus) IsValid() bool {
	switch e {
	case OrganizationProjectOrgParticipationStatusPending, OrganizationProjectOrgParticipationStatusAccepted, OrganizationProjectOrgParticipationStatusDeclined, OrganizationProjectOrgParticipationStatusRevoked:
		return true
	}
	return false
}

func (e OrganizationProjectOrgParticipationStatus) String() string {
	return string(e)
}

func (e *OrganizationProjectOrgParticipationStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationProjectOrgParticipationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationProjectOrgParticipationStatus", str)
	}
	return nil
}

func (e OrganizationProjectOrgParticipationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationProjectPurchaseStatus string

const (
	OrganizationProjectPurchaseStatusRequested OrganizationProjectPurchaseStatus = "REQUESTED"
	OrganizationProjectPurchaseStatusPurchased OrganizationProjectPurchaseStatus = "PURCHASED"
	OrganizationProjectPurchaseStatusCancelled OrganizationProjectPurchaseStatus = "CANCELLED"
)

var AllOrganizationProjectPurchaseStatus = []OrganizationProjectPurchaseStatus{
	OrganizationProjectPurchaseStatusRequested,
	OrganizationProjectPurchaseStatusPurchased,
	OrganizationProjectPurchaseStatusCancelled,
}

func (e OrganizationProjectPurchaseStatus) IsValid() bool {
	switch e {
	case OrganizationProjectPurchaseStatusRequested, OrganizationProjectPurchaseStatusPurchased, OrganizationProjectPurchaseStatusCancelled:
		return true
	}
	return false
}

func (e OrganizationProjectPurchaseStatus) String() string {
	return string(e)
}

func (e *OrganizationProjectPurchaseStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationProjectPurchaseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationProjectPurchaseStatus", str)
	}
	return nil
}

func (e OrganizationProjectPurchaseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OrganizationProjectTodoStatus string

const (
	OrganizationProjectTodoStatusOpen OrganizationProjectTodoStatus = "OPEN"
	OrganizationProjectTodoStatusDone OrganizationProjectTodoStatus = "DONE"
)

var AllOrganizationProjectTodoStatus = []OrganizationProjectTodoStatus{
	OrganizationProjectTodoStatusOpen,
	OrganizationProjectTodoStatusDone,
}

func (e OrganizationProjectTodoStatus) IsValid() bool {
	switch e {
	case OrganizationProjectTodoStatusOpen, OrganizationProjectTodoStatusDone:
		return true
	}
	return false
}

func (e OrganizationProjectTodoStatus) String() string {
	return string(e)
}

func (e *OrganizationProjectTodoStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationProjectTodoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationProjectTodoStatus", str)
	}
	return nil
}

func (e OrganizationProjectTodoStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Theme string

const (
	ThemeLight  Theme = "LIGHT"
	ThemeDark   Theme = "DARK"
	ThemeSystem Theme = "SYSTEM"
)

var AllTheme = []Theme{
	ThemeLight,
	ThemeDark,
	ThemeSystem,
}

func (e Theme) IsValid() bool {
	switch e {
	case ThemeLight, ThemeDark, ThemeSystem:
		return true
	}
	return false
}

func (e Theme) String() string {
	return string(e)
}

func (e *Theme) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Theme(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Theme", str)
	}
	return nil
}

func (e Theme) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "ADMIN"
	UserRoleModerator UserRole = "MODERATOR"
	UserRoleUser      UserRole = "USER"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleModerator,
	UserRoleUser,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleModerator, UserRoleUser:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
